// ============================================================
// Research Tree - node datum + global registry
// ------------------------------------------------------------
// A node is one "invention" in the tree. Nodes are faction-agnostic
// (shared definitions); per-faction progress lives on the map
// metadata (see research_faction.dm).
//
// Phase 0 ships a tiny stub tree so benches have something real to
// research. Phase 2 replaces build_research_tree() with the ~60-120
// nodes clustered from the crafting catalogue.
// ============================================================

// id => /datum/research_node
var/global/list/research_nodes = list()

// result-path string (recipe field i[3]) => required node id.
// Populated in build_research_tree(). A recipe present here is gated on
// its node being DONE for the faction instead of the legacy research
// thresholds; recipes NOT present here keep using thresholds unchanged.
var/global/list/recipe_node_requirements = list()

/proc/get_recipe_node_req(result_path_string)
	return recipe_node_requirements[result_path_string]

/datum/research_node
	var/id = null                    // unique string key, e.g. "basic_tools"
	var/name = "research node"       // display name
	var/category = "General"         // grouping (mirrors crafting subtitles)
	var/desc = ""                    // flavour / what it unlocks
	var/list/prereqs = list()        // list of node ids that must be DONE first
	var/cost_ticks = 100             // analysis ticks needed to complete
	var/min_bench_tier = 0           // lowest bench tier that can research this
	// Era this node belongs to (ordinal_age). Nodes at era_tier <= the map's
	// current ordinal_age are BASELINE: auto-granted to every faction and to
	// factionless players (you never re-research past eras). Only frontier
	// nodes (era_tier > current era) actually need bench/book/prototype work.
	var/era_tier = 0
	var/mode = RESEARCH_MODE_ANALYSIS
	var/list/unlocks = list()        // recipe ids / feature flags (wired in Phase 1)
	// Alternate-completion payloads (used in later phases):
	var/prototype_type = null        // PROTOTYPE mode: item type to build & consume
	var/book_subject = null          // BOOK mode: matching research-book subject

/datum/research_node/New(_id, _name, _category, _cost_ticks = 100, _min_bench_tier = 0, _mode = RESEARCH_MODE_ANALYSIS, list/_prereqs = null, _era_tier = 0, _prototype_type = null)
	..()
	id = _id
	name = _name
	category = _category
	cost_ticks = _cost_ticks
	min_bench_tier = _min_bench_tier
	mode = _mode
	era_tier = _era_tier
	prototype_type = _prototype_type
	if (_prereqs)
		prereqs = _prereqs

// Registers a node, warning on duplicate ids so tree authoring mistakes surface.
/proc/register_research_node(datum/research_node/N)
	if (!istype(N) || !N.id)
		return
	if (research_nodes[N.id])
		log_debug("research_tree: duplicate node id '[N.id]' ignored")
		return
	research_nodes[N.id] = N

/proc/get_research_node(node_id)
	return research_nodes[node_id]

// Called once at world setup. Phase 0 = stub content only.
/proc/build_research_tree()
	research_nodes = list()

	// Args: id, name, category(layer), cost_ticks, min_bench_tier, mode, prereqs, era_tier
	// Three intersecting layers (Industrial/Military/Health), each a set of
	// functional lines laddered across the 9 eras. Capstones (PROTOTYPE mode)
	// advance the age. Cross-branch prereqs make it a tree, not 3 ladders.
	// --- Industrial: Toolmaking ---
	register_research_node(new /datum/research_node("basic_tools", "Basic Toolmaking", "Industrial", 60, 0, RESEARCH_MODE_ANALYSIS, null, 0))
	register_research_node(new /datum/research_node("iron_tools", "Iron Tools", "Industrial", 130, 1, RESEARCH_MODE_ANALYSIS, list("basic_tools"), 2))
	register_research_node(new /datum/research_node("machined_tools", "Machined Tools", "Industrial", 200, 3, RESEARCH_MODE_ANALYSIS, list("iron_tools","steelmaking"), 4))
	register_research_node(new /datum/research_node("power_tools", "Power Tools", "Industrial", 270, 5, RESEARCH_MODE_ANALYSIS, list("machined_tools","electricity"), 6))
	// --- Industrial: Metallurgy ---
	// Prototype: a cast axehead mold (gated on stone_arms, era-0 baseline --
	// always available, so it can never be circular with bronze_working itself).
	register_research_node(new /datum/research_node("bronze_working", "Bronze Working", "Industrial", 142, 0, RESEARCH_MODE_PROTOTYPE, null, 1, /obj/item/weapon/clay/mold/axehead))
	// Prototype: a bronze ingot mold (gated on bronze_working, its own direct prereq).
	register_research_node(new /datum/research_node("iron_smithing", "Iron Smithing", "Industrial", 195, 1, RESEARCH_MODE_PROTOTYPE, list("bronze_working"), 2, /obj/item/weapon/clay/mold))
	register_research_node(new /datum/research_node("steelmaking", "Steelmaking", "Industrial", 200, 3, RESEARCH_MODE_ANALYSIS, list("iron_smithing"), 4))
	register_research_node(new /datum/research_node("alloys", "Alloys", "Industrial", 270, 5, RESEARCH_MODE_ANALYSIS, list("steelmaking"), 6))
	// --- Industrial: Construction ---
	register_research_node(new /datum/research_node("stone_masonry", "Stone Masonry", "Industrial", 95, 0, RESEARCH_MODE_ANALYSIS, null, 1))
	register_research_node(new /datum/research_node("medieval_construction", "Medieval Construction", "Industrial", 130, 1, RESEARCH_MODE_ANALYSIS, list("stone_masonry"), 2))
	register_research_node(new /datum/research_node("imperial_architecture", "Imperial Architecture", "Industrial", 165, 2, RESEARCH_MODE_ANALYSIS, list("medieval_construction"), 3))
	register_research_node(new /datum/research_node("reinforced_concrete", "Reinforced Concrete", "Industrial", 200, 3, RESEARCH_MODE_ANALYSIS, list("imperial_architecture","steelmaking"), 4))
	register_research_node(new /datum/research_node("modern_construction", "Modern Construction", "Industrial", 270, 5, RESEARCH_MODE_ANALYSIS, list("reinforced_concrete"), 6))
	// --- Industrial: Production ---
	register_research_node(new /datum/research_node("pottery_storage", "Pottery & Storage", "Industrial", 60, 0, RESEARCH_MODE_ANALYSIS, null, 0))
	register_research_node(new /datum/research_node("workshops", "Workshops", "Industrial", 130, 1, RESEARCH_MODE_ANALYSIS, list("pottery_storage"), 2))
	register_research_node(new /datum/research_node("printing_currency", "Printing & Currency", "Industrial", 165, 2, RESEARCH_MODE_ANALYSIS, list("workshops"), 3))
	register_research_node(new /datum/research_node("factories", "Factories", "Industrial", 200, 3, RESEARCH_MODE_ANALYSIS, list("printing_currency","steam_power"), 4))
	register_research_node(new /datum/research_node("assembly_line", "Assembly Line", "Industrial", 235, 4, RESEARCH_MODE_ANALYSIS, list("factories"), 5))
	register_research_node(new /datum/research_node("automation", "Automation", "Industrial", 305, 6, RESEARCH_MODE_ANALYSIS, list("assembly_line","electricity"), 7))
	// Prototype: an early electronic device (gated on assembly_line, era5, well
	// before this node's era8 -- assembly_line is baseline-granted by then).
	register_research_node(new /datum/research_node("digital_computing", "Digital Computing", "Industrial", 510, 7, RESEARCH_MODE_PROTOTYPE, list("automation","electricity"), 8, /obj/item/camera/coldwar))
	// --- Industrial: Textiles ---
	register_research_node(new /datum/research_node("weaving", "Weaving", "Industrial", 60, 0, RESEARCH_MODE_ANALYSIS, null, 0))
	register_research_node(new /datum/research_node("tailoring", "Tailoring", "Industrial", 95, 0, RESEARCH_MODE_ANALYSIS, list("weaving"), 1))
	register_research_node(new /datum/research_node("fine_garments", "Fine Garments", "Industrial", 165, 2, RESEARCH_MODE_ANALYSIS, list("tailoring"), 3))
	register_research_node(new /datum/research_node("textile_mills", "Textile Mills", "Industrial", 200, 3, RESEARCH_MODE_ANALYSIS, list("fine_garments","steam_power"), 4))
	register_research_node(new /datum/research_node("synthetics", "Synthetic Fabrics", "Industrial", 305, 6, RESEARCH_MODE_ANALYSIS, list("textile_mills"), 7))
	// --- Industrial: Furniture ---
	register_research_node(new /datum/research_node("basic_furniture", "Basic Furniture", "Industrial", 60, 0, RESEARCH_MODE_ANALYSIS, null, 0))
	register_research_node(new /datum/research_node("fine_furniture", "Fine Furniture", "Industrial", 130, 1, RESEARCH_MODE_ANALYSIS, list("basic_furniture"), 2))
	register_research_node(new /datum/research_node("manufactured_furniture", "Manufactured Furniture", "Industrial", 200, 3, RESEARCH_MODE_ANALYSIS, list("fine_furniture"), 4))
	register_research_node(new /datum/research_node("modern_furnishings", "Modern Furnishings", "Industrial", 270, 5, RESEARCH_MODE_ANALYSIS, list("manufactured_furniture"), 6))
	// --- Industrial: Power ---
	register_research_node(new /datum/research_node("watermills", "Watermills", "Industrial", 130, 1, RESEARCH_MODE_ANALYSIS, null, 2))
	// Prototype: a machined component (gated on basic_tools, era0 baseline --
	// placeholder until a dedicated "engine prototype" item exists).
	register_research_node(new /datum/research_node("steam_power", "Steam Power", "Industrial", 300, 3, RESEARCH_MODE_PROTOTYPE, list("watermills"), 4, /obj/item/weapon/material/handle))
	// Prototype: a spool of cable (gated on paved_infrastructure, era3, well
	// before this node's era5).
	register_research_node(new /datum/research_node("electricity", "Electricity", "Industrial", 352, 4, RESEARCH_MODE_PROTOTYPE, list("steam_power"), 5, /obj/item/stack/cable_coil))
	register_research_node(new /datum/research_node("combustion", "Combustion Engine", "Industrial", 235, 4, RESEARCH_MODE_ANALYSIS, list("steam_power","steelmaking"), 5))
	// Prototype: a geiger counter (gated on factories, era4, well before this
	// node's era7).
	register_research_node(new /datum/research_node("nuclear_power", "Nuclear Power", "Industrial", 458, 6, RESEARCH_MODE_PROTOTYPE, list("combustion"), 7, /obj/item/weapon/geiger_counter))
	// --- Industrial: Vehicles ---
	register_research_node(new /datum/research_node("carts", "Carts", "Industrial", 95, 0, RESEARCH_MODE_ANALYSIS, null, 1))
	register_research_node(new /datum/research_node("wagons_ships", "Wagons & Ships", "Industrial", 165, 2, RESEARCH_MODE_ANALYSIS, list("carts"), 3))
	register_research_node(new /datum/research_node("rail_steam", "Rail & Steam", "Industrial", 200, 3, RESEARCH_MODE_ANALYSIS, list("wagons_ships","steam_power"), 4))
	register_research_node(new /datum/research_node("automobiles", "Automobiles", "Industrial", 235, 4, RESEARCH_MODE_ANALYSIS, list("rail_steam","combustion"), 5))
	register_research_node(new /datum/research_node("aviation_rocketry", "Aviation & Rocketry", "Industrial", 305, 6, RESEARCH_MODE_ANALYSIS, list("automobiles","combustion","alloys"), 7))
	// --- Industrial: Infrastructure ---
	register_research_node(new /datum/research_node("roads", "Roads", "Industrial", 95, 0, RESEARCH_MODE_ANALYSIS, null, 1))
	register_research_node(new /datum/research_node("paved_infrastructure", "Paved Infrastructure", "Industrial", 165, 2, RESEARCH_MODE_ANALYSIS, list("roads"), 3))
	register_research_node(new /datum/research_node("utilities", "Utilities", "Industrial", 235, 4, RESEARCH_MODE_ANALYSIS, list("paved_infrastructure","electricity"), 5))
	// --- Military: Melee ---
	register_research_node(new /datum/research_node("stone_arms", "Stone Arms", "Military", 60, 0, RESEARCH_MODE_ANALYSIS, null, 0))
	register_research_node(new /datum/research_node("bronze_weapons", "Bronze Weapons", "Military", 95, 0, RESEARCH_MODE_ANALYSIS, list("stone_arms"), 1))
	register_research_node(new /datum/research_node("steel_blades", "Steel Blades", "Military", 130, 1, RESEARCH_MODE_ANALYSIS, list("bronze_weapons","iron_smithing"), 2))
	register_research_node(new /datum/research_node("bayonets", "Bayonets", "Military", 165, 2, RESEARCH_MODE_ANALYSIS, list("steel_blades"), 3))
	// --- Military: Archery ---
	register_research_node(new /datum/research_node("archery", "Archery", "Military", 60, 0, RESEARCH_MODE_ANALYSIS, null, 0))
	register_research_node(new /datum/research_node("crossbows", "Crossbows", "Military", 130, 1, RESEARCH_MODE_ANALYSIS, list("archery"), 2))
	// --- Military: Firearms ---
	// Prototype: a pouch of black powder (gated on iron_smithing, its own
	// direct prereq -- see the recipe_node_requirements fix below, this item
	// was previously misclassified onto fine_garments).
	register_research_node(new /datum/research_node("gunpowder", "Gunpowder", "Military", 248, 2, RESEARCH_MODE_PROTOTYPE, list("iron_smithing"), 3, /obj/item/weapon/reagent_containers/food/drinks/gunpowder))
	register_research_node(new /datum/research_node("rifling", "Rifling", "Military", 200, 3, RESEARCH_MODE_ANALYSIS, list("gunpowder","steelmaking"), 4))
	register_research_node(new /datum/research_node("cartridge_ammo", "Cartridge Ammunition", "Military", 235, 4, RESEARCH_MODE_ANALYSIS, list("rifling"), 5))
	register_research_node(new /datum/research_node("bolt_action", "Bolt-Action", "Military", 270, 5, RESEARCH_MODE_ANALYSIS, list("cartridge_ammo"), 6))
	register_research_node(new /datum/research_node("automatic_weapons", "Automatic Weapons", "Military", 305, 6, RESEARCH_MODE_ANALYSIS, list("bolt_action"), 7))
	register_research_node(new /datum/research_node("modern_firearms", "Modern Firearms", "Military", 340, 7, RESEARCH_MODE_ANALYSIS, list("automatic_weapons"), 8))
	// --- Military: Artillery ---
	register_research_node(new /datum/research_node("siege_engines", "Siege Engines", "Military", 130, 1, RESEARCH_MODE_ANALYSIS, null, 2))
	register_research_node(new /datum/research_node("cannon", "Cannon", "Military", 165, 2, RESEARCH_MODE_ANALYSIS, list("siege_engines","imperial_architecture"), 3))
	register_research_node(new /datum/research_node("field_artillery", "Field Artillery", "Military", 200, 3, RESEARCH_MODE_ANALYSIS, list("cannon","steelmaking"), 4))
	// Prototype: a tank shell casing (gated on field_artillery, its own direct prereq).
	register_research_node(new /datum/research_node("mechanized_war", "Mechanized Warfare", "Military", 405, 5, RESEARCH_MODE_PROTOTYPE, list("field_artillery","combustion","steelmaking"), 6, /obj/item/stack/ammopart/casing/tank))
	register_research_node(new /datum/research_node("missiles", "Missiles", "Military", 305, 6, RESEARCH_MODE_ANALYSIS, list("mechanized_war","aviation_rocketry"), 7))
	// --- Military: Armor ---
	register_research_node(new /datum/research_node("padded_armor", "Padded Armor", "Military", 60, 0, RESEARCH_MODE_ANALYSIS, null, 0))
	register_research_node(new /datum/research_node("mail_plate", "Mail & Plate", "Military", 130, 1, RESEARCH_MODE_ANALYSIS, list("padded_armor"), 2))
	register_research_node(new /datum/research_node("fortifications", "Fortifications", "Military", 165, 2, RESEARCH_MODE_ANALYSIS, list("mail_plate","imperial_architecture"), 3))
	register_research_node(new /datum/research_node("trench_warfare", "Trench Warfare", "Military", 235, 4, RESEARCH_MODE_ANALYSIS, list("fortifications"), 5))
	register_research_node(new /datum/research_node("modern_armor", "Modern Armor", "Military", 305, 6, RESEARCH_MODE_ANALYSIS, list("trench_warfare","alloys"), 7))
	// --- Health: Medicine ---
	register_research_node(new /datum/research_node("herbalism", "Herbalism", "Health", 60, 0, RESEARCH_MODE_ANALYSIS, null, 0))
	register_research_node(new /datum/research_node("apothecary", "Apothecary", "Health", 130, 1, RESEARCH_MODE_ANALYSIS, list("herbalism"), 2))
	register_research_node(new /datum/research_node("pharmacology", "Pharmacology", "Health", 235, 4, RESEARCH_MODE_ANALYSIS, list("apothecary","printing_currency"), 5))
	register_research_node(new /datum/research_node("modern_medicine", "Modern Medicine", "Health", 305, 6, RESEARCH_MODE_ANALYSIS, list("pharmacology"), 7))
	// --- Health: Surgery ---
	register_research_node(new /datum/research_node("field_surgery", "Field Surgery", "Health", 95, 0, RESEARCH_MODE_ANALYSIS, list("bronze_working"), 1))
	register_research_node(new /datum/research_node("surgical_theory", "Surgical Theory", "Health", 165, 2, RESEARCH_MODE_ANALYSIS, list("field_surgery","printing_currency"), 3))
	register_research_node(new /datum/research_node("anesthetic_surgery", "Anesthetic Surgery", "Health", 235, 4, RESEARCH_MODE_ANALYSIS, list("surgical_theory"), 5))
	register_research_node(new /datum/research_node("modern_surgery", "Modern Surgery", "Health", 305, 6, RESEARCH_MODE_ANALYSIS, list("anesthetic_surgery"), 7))
	// --- Health: Sanitation ---
	register_research_node(new /datum/research_node("hygiene", "Hygiene", "Health", 95, 0, RESEARCH_MODE_ANALYSIS, null, 1))
	register_research_node(new /datum/research_node("sanitation", "Sanitation", "Health", 165, 2, RESEARCH_MODE_ANALYSIS, list("hygiene"), 3))
	register_research_node(new /datum/research_node("germ_theory", "Germ Theory", "Health", 235, 4, RESEARCH_MODE_ANALYSIS, list("sanitation"), 5))
	register_research_node(new /datum/research_node("public_health", "Public Health", "Health", 305, 6, RESEARCH_MODE_ANALYSIS, list("germ_theory"), 7))

	// Phase 2: full catalogue mapping. Generated from config/crafting/
	// material_recipes_*.txt (1325 unique result paths across all 9 faction
	// files) via keyword+era classification, spot-checked and corrected for
	// misclassifications. Unmapped paths (not listed here) keep the legacy
	// threshold gate unchanged (see generate_recipes_civs in civ_recipes.dm).
	recipe_node_requirements = list(
		"/obj/covers/carpet/blackcarpet" = "pottery_storage",
		"/obj/covers/carpet/bluecarpet" = "pottery_storage",
		"/obj/covers/carpet/greencarpet" = "pottery_storage",
		"/obj/covers/carpet/orangecarpet" = "pottery_storage",
		"/obj/covers/carpet/pinkcarpet" = "pottery_storage",
		"/obj/covers/carpet/purplecarpet" = "pottery_storage",
		"/obj/covers/carpet/redcarpet" = "pottery_storage",
		"/obj/covers/carpet/tealcarpet" = "pottery_storage",
		"/obj/covers/carpet/whitecarpet" = "pottery_storage",
		"/obj/covers/cobblestone" = "imperial_architecture",
		"/obj/covers/cobblestone/stairs" = "stone_masonry",
		"/obj/covers/concretefloor" = "imperial_architecture",
		"/obj/covers/decorative_marbletile" = "printing_currency",
		"/obj/covers/decorative_marbletile/black" = "printing_currency",
		"/obj/covers/decorative_marbletile/pink" = "printing_currency",
		"/obj/covers/fancywood" = "imperial_architecture",
		"/obj/covers/jail/steeljail" = "workshops",
		"/obj/covers/jail/woodjail" = "pottery_storage",
		"/obj/covers/marble_checkerboard" = "imperial_architecture",
		"/obj/covers/marble_checkerboard/pink" = "imperial_architecture",
		"/obj/covers/marble_checkerboard/pink/reverse" = "imperial_architecture",
		"/obj/covers/marble_checkerboard/reverse" = "imperial_architecture",
		"/obj/covers/marble_grid" = "imperial_architecture",
		"/obj/covers/marble_wall" = "stone_masonry",
		"/obj/covers/marble_wall/classic" = "stone_masonry",
		"/obj/covers/marble_wall/grecian" = "stone_masonry",
		"/obj/covers/marble_wall/grecian/archway" = "pottery_storage",
		"/obj/covers/marble_wall/grecian/archway/modern" = "printing_currency",
		"/obj/covers/marblefloor" = "imperial_architecture",
		"/obj/covers/marbletile" = "printing_currency",
		"/obj/covers/marbletile/black" = "printing_currency",
		"/obj/covers/marbletile/pink" = "printing_currency",
		"/obj/covers/ornatemarblefloor" = "imperial_architecture",
		"/obj/covers/ornatemarblefloor/black" = "imperial_architecture",
		"/obj/covers/raw_marblefloor" = "stone_masonry",
		"/obj/covers/raw_marblefloor/black" = "stone_masonry",
		"/obj/covers/raw_marblefloor/pink" = "stone_masonry",
		"/obj/covers/road" = "paved_infrastructure",
		"/obj/covers/roads/cobble" = "paved_infrastructure",
		"/obj/covers/roads/modern" = "paved_infrastructure",
		"/obj/covers/roads/roman" = "paved_infrastructure",
		"/obj/covers/roads/sandstone" = "roads",
		"/obj/covers/sandstone" = "stone_masonry",
		"/obj/covers/sandstone/brick" = "stone_masonry",
		"/obj/covers/sandstone/slab" = "stone_masonry",
		"/obj/covers/sandstone/slab/red" = "stone_masonry",
		"/obj/covers/sandstone/stairs" = "stone_masonry",
		"/obj/covers/sandstone/tile" = "pottery_storage",
		"/obj/covers/sandstone/tile/decorative" = "pottery_storage",
		"/obj/covers/sandstone/tile/decorative/red" = "pottery_storage",
		"/obj/covers/sandstone_smooth_wall/plain" = "stone_masonry",
		"/obj/covers/sandstone_wall/classic" = "stone_masonry",
		"/obj/covers/sandstone_wall/classic/archway" = "pottery_storage",
		"/obj/covers/sandstone_wall/classic/archway/red" = "pottery_storage",
		"/obj/covers/sandstone_wall/classic/red" = "stone_masonry",
		"/obj/covers/sandstone_wall/egyptian" = "stone_masonry",
		"/obj/covers/sandstone_wall/egyptian/archway" = "pottery_storage",
		"/obj/covers/sidewalk" = "printing_currency",
		"/obj/covers/slatefloor" = "stone_masonry",
		"/obj/covers/steelplating" = "imperial_architecture",
		"/obj/covers/steelplating/white" = "imperial_architecture",
		"/obj/covers/stone/slab/decorative" = "stone_masonry",
		"/obj/covers/stone_wall" = "stone_masonry",
		"/obj/covers/stone_wall/brick" = "imperial_architecture",
		"/obj/covers/stone_wall/brick/archway" = "imperial_architecture",
		"/obj/covers/stone_wall/classic" = "stone_masonry",
		"/obj/covers/stone_wall/classic/archway" = "pottery_storage",
		"/obj/covers/stone_wall/fortress" = "stone_masonry",
		"/obj/covers/stone_wall/fortress/archway" = "pottery_storage",
		"/obj/covers/stone_wall/fortress/sandstone" = "stone_masonry",
		"/obj/covers/stone_wall/mayan" = "stone_masonry",
		"/obj/covers/stone_wall/roman" = "stone_masonry",
		"/obj/covers/stone_wall/roman/modern" = "reinforced_concrete",
		"/obj/covers/stonebrickfloor" = "imperial_architecture",
		"/obj/covers/straw_wall" = "stone_masonry",
		"/obj/covers/tatami" = "stone_masonry",
		"/obj/covers/tatami_dark" = "stone_masonry",
		"/obj/covers/tatami_dark_vertical" = "stone_masonry",
		"/obj/covers/tatami_vertical" = "stone_masonry",
		"/obj/covers/thatch" = "stone_masonry",
		"/obj/covers/thatch2" = "stone_masonry",
		"/obj/covers/wood" = "stone_masonry",
		"/obj/covers/wood/stairs" = "stone_masonry",
		"/obj/covers/wood_wall/adjustable" = "stone_masonry",
		"/obj/covers/wood_wall/aztec" = "stone_masonry",
		"/obj/covers/wood_wall/log" = "stone_masonry",
		"/obj/covers/wood_wall/log/corner" = "stone_masonry",
		"/obj/covers/wood_wall/nordic" = "stone_masonry",
		"/obj/item/ammo_casing/arrow" = "archery",
		"/obj/item/ammo_casing/bolt" = "bronze_weapons",
		"/obj/item/ammo_casing/chemdart/bone" = "stone_arms",
		"/obj/item/ammo_casing/stone" = "archery",
		"/obj/item/ammo_magazine/emptybelt" = "cartridge_ammo",
		"/obj/item/ammo_magazine/emptyclip" = "rifling",
		"/obj/item/ammo_magazine/emptymagazine" = "cartridge_ammo",
		"/obj/item/ammo_magazine/emptymagazine/pistol" = "rifling",
		"/obj/item/ammo_magazine/emptymagazine/pistol/a45" = "rifling",
		"/obj/item/ammo_magazine/emptymagazine/rifle" = "cartridge_ammo",
		"/obj/item/ammo_magazine/emptypouch" = "gunpowder",
		"/obj/item/ammo_magazine/emptyspeedloader" = "gunpowder",
		"/obj/item/camera" = "automation",
		"/obj/item/camera/coldwar" = "assembly_line",
		"/obj/item/camera/early" = "printing_currency",
		"/obj/item/camera/earlymodern" = "factories",
		"/obj/item/camera_film" = "printing_currency",
		"/obj/item/cannon_ball" = "cannon",
		"/obj/item/catapult_ball" = "siege_engines",
		"/obj/item/clothing/accessory/armband/armbangle" = "weaving",
		"/obj/item/clothing/accessory/armband/armbangle/bronze" = "weaving",
		"/obj/item/clothing/accessory/armband/armbangle/copper" = "weaving",
		"/obj/item/clothing/accessory/armband/armbangle/gold" = "weaving",
		"/obj/item/clothing/accessory/armband/armbangle/silver" = "weaving",
		"/obj/item/clothing/accessory/armband/indian2" = "weaving",
		"/obj/item/clothing/accessory/armband/indian2/pygmy" = "weaving",
		"/obj/item/clothing/accessory/armband/punk" = "bayonets",
		"/obj/item/clothing/accessory/armband/talisman" = "weaving",
		"/obj/item/clothing/accessory/armor/nomads/civiliankevlar" = "modern_armor",
		"/obj/item/clothing/accessory/custom/apron" = "fine_garments",
		"/obj/item/clothing/accessory/custom/armband" = "weaving",
		"/obj/item/clothing/accessory/custom/bowtie" = "fine_garments",
		"/obj/item/clothing/accessory/custom/cape" = "weaving",
		"/obj/item/clothing/accessory/custom/priest_band" = "fine_garments",
		"/obj/item/clothing/accessory/custom/sash" = "weaving",
		"/obj/item/clothing/accessory/custom/scarf" = "fine_garments",
		"/obj/item/clothing/accessory/custom/tabard" = "weaving",
		"/obj/item/clothing/accessory/custom/tie" = "fine_garments",
		"/obj/item/clothing/accessory/holster/hip" = "fine_garments",
		"/obj/item/clothing/accessory/holster/hip/double" = "fine_garments",
		"/obj/item/clothing/accessory/medal/bronze" = "tailoring",
		"/obj/item/clothing/accessory/medal/gold" = "tailoring",
		"/obj/item/clothing/accessory/medal/silver" = "tailoring",
		"/obj/item/clothing/accessory/ruffle/neck" = "tailoring",
		"/obj/item/clothing/accessory/storage/coinpouch" = "weaving",
		"/obj/item/clothing/accessory/storage/coinpouch/gator_wallet" = "fine_garments",
		"/obj/item/clothing/accessory/storage/coinpouch/lizard_wallet" = "fine_garments",
		"/obj/item/clothing/accessory/storage/coinpouch/wallet" = "fine_garments",
		"/obj/item/clothing/accessory/storage/passport" = "fine_garments",
		"/obj/item/clothing/accessory/storage/sheath" = "steel_blades",
		"/obj/item/clothing/accessory/storage/sheath/daisho" = "tailoring",
		"/obj/item/clothing/accessory/storage/sheath/katana" = "bronze_weapons",
		"/obj/item/clothing/accessory/storage/sheath/longer" = "steel_blades",
		"/obj/item/clothing/accessory/storage/sheath/longsword" = "steel_blades",
		"/obj/item/clothing/accessory/storage/webbing" = "fine_garments",
		"/obj/item/clothing/accessory/storage/webbing/green_webbing" = "fine_garments",
		"/obj/item/clothing/accessory/storage/webbing/khaki_webbing" = "fine_garments",
		"/obj/item/clothing/accessory/storage/webbing/light" = "fine_garments",
		"/obj/item/clothing/accessory/suspenders" = "fine_garments",
		"/obj/item/clothing/accessory/suspenders/dark" = "fine_garments",
		"/obj/item/clothing/accessory/wearable_sign" = "weaving",
		"/obj/item/clothing/glasses/eyepatch" = "weaving",
		"/obj/item/clothing/glasses/gglasses" = "textile_mills",
		"/obj/item/clothing/glasses/monocle" = "fine_garments",
		"/obj/item/clothing/glasses/pilot" = "textile_mills",
		"/obj/item/clothing/glasses/redlense" = "textile_mills",
		"/obj/item/clothing/glasses/regular" = "textile_mills",
		"/obj/item/clothing/glasses/sunglasses" = "textile_mills",
		"/obj/item/clothing/glasses/sunglasses/blindfold" = "weaving",
		"/obj/item/clothing/glasses/sunglasses/large" = "textile_mills",
		"/obj/item/clothing/glasses/univisorcyan" = "textile_mills",
		"/obj/item/clothing/glasses/univisorflashy" = "textile_mills",
		"/obj/item/clothing/glasses/univisorgreen" = "textile_mills",
		"/obj/item/clothing/glasses/univisorred" = "textile_mills",
		"/obj/item/clothing/glasses/univisorwhite" = "textile_mills",
		"/obj/item/clothing/glasses/univisoryellow" = "textile_mills",
		"/obj/item/clothing/gloves/motorist" = "textile_mills",
		"/obj/item/clothing/gloves/oven" = "fine_garments",
		"/obj/item/clothing/gloves/thick/leather" = "weaving",
		"/obj/item/clothing/gloves/thick/leather/black" = "weaving",
		"/obj/item/clothing/gloves/thick/leather/brown" = "weaving",
		"/obj/item/clothing/gloves/thick/leather/grey" = "weaving",
		"/obj/item/clothing/gloves/thick/leather/orc" = "weaving",
		"/obj/item/clothing/gloves/thick/leather/pink" = "weaving",
		"/obj/item/clothing/gloves/thick/leather/white" = "weaving",
		"/obj/item/clothing/gloves/watch/goldwatch" = "textile_mills",
		"/obj/item/clothing/gloves/watch/specialwatch" = "textile_mills",
		"/obj/item/clothing/gloves/watch/watch" = "textile_mills",
		"/obj/item/clothing/head/ainu_bandana" = "weaving",
		"/obj/item/clothing/head/artisan" = "tailoring",
		"/obj/item/clothing/head/bandit" = "fine_garments",
		"/obj/item/clothing/head/bearpelt/black" = "weaving",
		"/obj/item/clothing/head/bearpelt/brown" = "weaving",
		"/obj/item/clothing/head/bearpelt/white" = "weaving",
		"/obj/item/clothing/head/bicorne_british_soldier" = "fine_garments",
		"/obj/item/clothing/head/bisonpelt" = "weaving",
		"/obj/item/clothing/head/blue_sailorberet" = "fine_garments",
		"/obj/item/clothing/head/bowler_hat" = "fine_garments",
		"/obj/item/clothing/head/capotain" = "fine_garments",
		"/obj/item/clothing/head/capotain/pilgrim" = "fine_garments",
		"/obj/item/clothing/head/cavalier" = "tailoring",
		"/obj/item/clothing/head/chief_hat" = "fine_garments",
		"/obj/item/clothing/head/count_hat" = "fine_garments",
		"/obj/item/clothing/head/cowboyhat" = "fine_garments",
		"/obj/item/clothing/head/cowboyhat2" = "fine_garments",
		"/obj/item/clothing/head/custom/custom_beanie" = "textile_mills",
		"/obj/item/clothing/head/custom/custombandana" = "fine_garments",
		"/obj/item/clothing/head/custom/customberet" = "fine_garments",
		"/obj/item/clothing/head/custom/customhood" = "weaving",
		"/obj/item/clothing/head/custom/customnoblehat" = "tailoring",
		"/obj/item/clothing/head/custom/fieldcap" = "textile_mills",
		"/obj/item/clothing/head/custom/hijab" = "tailoring",
		"/obj/item/clothing/head/custom/kippa" = "tailoring",
		"/obj/item/clothing/head/custom/pimp_hat" = "textile_mills",
		"/obj/item/clothing/head/custom/taqiyah" = "tailoring",
		"/obj/item/clothing/head/custom_feathered_hat" = "fine_garments",
		"/obj/item/clothing/head/custom_hennin" = "tailoring",
		"/obj/item/clothing/head/custom_keffiyeh" = "tailoring",
		"/obj/item/clothing/head/custom_off_cap" = "textile_mills",
		"/obj/item/clothing/head/deshret" = "weaving",
		"/obj/item/clothing/head/egyptian_headdress_black" = "weaving",
		"/obj/item/clothing/head/egyptian_headdress_blue" = "weaving",
		"/obj/item/clothing/head/egyptian_headdress_red" = "weaving",
		"/obj/item/clothing/head/feathered_hat" = "fine_garments",
		"/obj/item/clothing/head/fiendish" = "weaving",
		"/obj/item/clothing/head/flatcap1" = "textile_mills",
		"/obj/item/clothing/head/flatcap2" = "textile_mills",
		"/obj/item/clothing/head/flatcap3" = "textile_mills",
		"/obj/item/clothing/head/foxpelt" = "weaving",
		"/obj/item/clothing/head/foxpelt/white" = "weaving",
		"/obj/item/clothing/head/furcap" = "fine_garments",
		"/obj/item/clothing/head/furhat" = "fine_garments",
		"/obj/item/clothing/head/furhat/bison" = "fine_garments",
		"/obj/item/clothing/head/gat" = "tailoring",
		"/obj/item/clothing/head/gatorpelt" = "weaving",
		"/obj/item/clothing/head/goatpelt" = "weaving",
		"/obj/item/clothing/head/hedjet" = "weaving",
		"/obj/item/clothing/head/helmet/aged_eisenbruck" = "padded_armor",
		"/obj/item/clothing/head/helmet/bone" = "padded_armor",
		"/obj/item/clothing/head/helmet/brown_eisenbruck" = "padded_armor",
		"/obj/item/clothing/head/helmet/chitin" = "padded_armor",
		"/obj/item/clothing/head/helmet/constable" = "trench_warfare",
		"/obj/item/clothing/head/helmet/gold_crown" = "padded_armor",
		"/obj/item/clothing/head/helmet/grey_eisenbruck" = "padded_armor",
		"/obj/item/clothing/head/helmet/hatchigane" = "padded_armor",
		"/obj/item/clothing/head/helmet/jingasa" = "padded_armor",
		"/obj/item/clothing/head/helmet/kasa" = "padded_armor",
		"/obj/item/clothing/head/helmet/khepresh" = "padded_armor",
		"/obj/item/clothing/head/helmet/leather" = "padded_armor",
		"/obj/item/clothing/head/helmet/leather_infantry" = "fortifications",
		"/obj/item/clothing/head/helmet/leather_infantry/blue" = "fortifications",
		"/obj/item/clothing/head/helmet/leather_infantry/brown" = "fortifications",
		"/obj/item/clothing/head/helmet/leather_infantry/red" = "fortifications",
		"/obj/item/clothing/head/helmet/leather_skullcap" = "padded_armor",
		"/obj/item/clothing/head/helmet/medieval/emirate" = "padded_armor",
		"/obj/item/clothing/head/helmet/medieval/nomads/arab" = "padded_armor",
		"/obj/item/clothing/head/helmet/medieval/nomads/arab2" = "padded_armor",
		"/obj/item/clothing/head/helmet/medieval/nomads/arab3" = "padded_armor",
		"/obj/item/clothing/head/helmet/medieval/nomads/arab4" = "padded_armor",
		"/obj/item/clothing/head/helmet/modern/hardhat" = "fortifications",
		"/obj/item/clothing/head/helmet/modern/hardhat/orange" = "fortifications",
		"/obj/item/clothing/head/helmet/modern/hardhat/yellow" = "fortifications",
		"/obj/item/clothing/head/helmet/montefortino" = "padded_armor",
		"/obj/item/clothing/head/helmet/napoleonic/bearskin" = "fortifications",
		"/obj/item/clothing/head/helmet/napoleonic/bearskin/brown" = "fortifications",
		"/obj/item/clothing/head/helmet/napoleonic/bearskin/white" = "fortifications",
		"/obj/item/clothing/head/helmet/napoleonic/dragoon" = "fortifications",
		"/obj/item/clothing/head/helmet/phrigian" = "padded_armor",
		"/obj/item/clothing/head/helmet/samurai/guard" = "padded_armor",
		"/obj/item/clothing/head/helmet/samurai/guard/black" = "padded_armor",
		"/obj/item/clothing/head/helmet/samurai/guard/blue" = "padded_armor",
		"/obj/item/clothing/head/helmet/samurai/guard/red" = "padded_armor",
		"/obj/item/clothing/head/helmet/silver_crown" = "padded_armor",
		"/obj/item/clothing/head/hooded_cape" = "tailoring",
		"/obj/item/clothing/head/kerchief" = "fine_garments",
		"/obj/item/clothing/head/laurelcrown" = "tailoring",
		"/obj/item/clothing/head/laurelcrown/gold" = "weaving",
		"/obj/item/clothing/head/leaves" = "weaving",
		"/obj/item/clothing/head/leaves/crown" = "tailoring",
		"/obj/item/clothing/head/lionpelt" = "weaving",
		"/obj/item/clothing/head/lizardpelt" = "weaving",
		"/obj/item/clothing/head/mayan_headdress" = "weaving",
		"/obj/item/clothing/head/nbc" = "textile_mills",
		"/obj/item/clothing/head/nbc/olive" = "textile_mills",
		"/obj/item/clothing/head/nemes" = "weaving",
		"/obj/item/clothing/head/nun_hood" = "fine_garments",
		"/obj/item/clothing/head/nurse" = "fine_garments",
		"/obj/item/clothing/head/pakol" = "weaving",
		"/obj/item/clothing/head/pantherpelt" = "weaving",
		"/obj/item/clothing/head/pharoah" = "weaving",
		"/obj/item/clothing/head/phrigian_hat" = "tailoring",
		"/obj/item/clothing/head/phrigian_hat/blue" = "tailoring",
		"/obj/item/clothing/head/phrigian_hat/doge" = "tailoring",
		"/obj/item/clothing/head/phrigian_hat/red" = "tailoring",
		"/obj/item/clothing/head/piratebandana1" = "fine_garments",
		"/obj/item/clothing/head/plaguedoctor" = "tailoring",
		"/obj/item/clothing/head/pschent" = "weaving",
		"/obj/item/clothing/head/red_sailorberet" = "fine_garments",
		"/obj/item/clothing/head/rice_hat" = "fine_garments",
		"/obj/item/clothing/head/roundcap" = "fine_garments",
		"/obj/item/clothing/head/semitic_cap" = "weaving",
		"/obj/item/clothing/head/sheeppelt" = "weaving",
		"/obj/item/clothing/head/sombrero" = "fine_garments",
		"/obj/item/clothing/head/steppe_shaman" = "weaving",
		"/obj/item/clothing/head/strawhat" = "weaving",
		"/obj/item/clothing/head/tarred_hat" = "fine_garments",
		"/obj/item/clothing/head/ten_gallon" = "textile_mills",
		"/obj/item/clothing/head/top_hat" = "textile_mills",
		"/obj/item/clothing/head/traffic_police" = "textile_mills",
		"/obj/item/clothing/head/tricorne_black" = "fine_garments",
		"/obj/item/clothing/head/turban" = "tailoring",
		"/obj/item/clothing/head/turban/imam" = "tailoring",
		"/obj/item/clothing/head/turban/sultan" = "tailoring",
		"/obj/item/clothing/head/vaquerohat" = "fine_garments",
		"/obj/item/clothing/head/wolfpelt" = "weaving",
		"/obj/item/clothing/head/wolfpelt/white" = "weaving",
		"/obj/item/clothing/head/ww2/sov_ushanka/nomads" = "textile_mills",
		"/obj/item/clothing/head/zulu_umghele" = "weaving",
		"/obj/item/clothing/mask/balaclava" = "textile_mills",
		"/obj/item/clothing/mask/bat" = "textile_mills",
		"/obj/item/clothing/mask/bear" = "textile_mills",
		"/obj/item/clothing/mask/bee" = "textile_mills",
		"/obj/item/clothing/mask/chitinmask" = "weaving",
		"/obj/item/clothing/mask/cow" = "textile_mills",
		"/obj/item/clothing/mask/frog" = "textile_mills",
		"/obj/item/clothing/mask/gas/british" = "fine_garments",
		"/obj/item/clothing/mask/gas/german" = "fine_garments",
		"/obj/item/clothing/mask/gas/modern" = "textile_mills",
		"/obj/item/clothing/mask/gas/modern2" = "textile_mills",
		"/obj/item/clothing/mask/gorilla" = "textile_mills",
		"/obj/item/clothing/mask/jackal" = "textile_mills",
		"/obj/item/clothing/mask/joy" = "synthetics",
		"/obj/item/clothing/mask/owl" = "textile_mills",
		"/obj/item/clothing/mask/pig" = "textile_mills",
		"/obj/item/clothing/mask/plaguedoctor" = "tailoring",
		"/obj/item/clothing/mask/rat" = "textile_mills",
		"/obj/item/clothing/mask/raven" = "textile_mills",
		"/obj/item/clothing/mask/shemagh" = "tailoring",
		"/obj/item/clothing/mask/shemagh/greykerchief" = "fine_garments",
		"/obj/item/clothing/mask/shemagh/redkerchief" = "fine_garments",
		"/obj/item/clothing/mask/skullmask" = "weaving",
		"/obj/item/clothing/mask/smokable/cigarette" = "fine_garments",
		"/obj/item/clothing/mask/smokable/cigarette/cigar" = "weaving",
		"/obj/item/clothing/mask/smokable/cigarette/cigar/havana" = "fine_garments",
		"/obj/item/clothing/mask/smokable/cigarette/joint" = "fine_garments",
		"/obj/item/clothing/mask/smokable/pipe" = "roads",
		"/obj/item/clothing/mask/sterile" = "anesthetic_surgery",
		"/obj/item/clothing/mask/wooden" = "weaving",
		"/obj/item/clothing/mask/wooden/african" = "tailoring",
		"/obj/item/clothing/mask/wooden/expressive" = "weaving",
		"/obj/item/clothing/shoes/aztec_sandals" = "weaving",
		"/obj/item/clothing/shoes/blackboots" = "fine_garments",
		"/obj/item/clothing/shoes/fur" = "weaving",
		"/obj/item/clothing/shoes/fur/black" = "weaving",
		"/obj/item/clothing/shoes/fur/brown" = "weaving",
		"/obj/item/clothing/shoes/fur/grey" = "weaving",
		"/obj/item/clothing/shoes/fur/orc" = "weaving",
		"/obj/item/clothing/shoes/fur/pink" = "weaving",
		"/obj/item/clothing/shoes/fur/white" = "weaving",
		"/obj/item/clothing/shoes/gator_ankleboots" = "fine_garments",
		"/obj/item/clothing/shoes/gator_laceup" = "textile_mills",
		"/obj/item/clothing/shoes/geta" = "tailoring",
		"/obj/item/clothing/shoes/laceup" = "textile_mills",
		"/obj/item/clothing/shoes/laceup/brown" = "textile_mills",
		"/obj/item/clothing/shoes/leather" = "textile_mills",
		"/obj/item/clothing/shoes/leatherboots" = "apothecary",
		"/obj/item/clothing/shoes/lizard_ankleboots" = "fine_garments",
		"/obj/item/clothing/shoes/lizard_laceup" = "textile_mills",
		"/obj/item/clothing/shoes/medieval" = "tailoring",
		"/obj/item/clothing/shoes/medieval/arab" = "tailoring",
		"/obj/item/clothing/shoes/medieval/emirate" = "tailoring",
		"/obj/item/clothing/shoes/punk" = "textile_mills",
		"/obj/item/clothing/shoes/riding1" = "fine_garments",
		"/obj/item/clothing/shoes/riding1/gator_cowboy" = "fine_garments",
		"/obj/item/clothing/shoes/riding1/lizard_cowboy" = "fine_garments",
		"/obj/item/clothing/shoes/riding2" = "fine_garments",
		"/obj/item/clothing/shoes/roman" = "weaving",
		"/obj/item/clothing/shoes/sandal" = "weaving",
		"/obj/item/clothing/shoes/sneakers/courier" = "textile_mills",
		"/obj/item/clothing/shoes/soldiershoes" = "fine_garments",
		"/obj/item/clothing/shoes/steppe_shoes" = "weaving",
		"/obj/item/clothing/shoes/workboots" = "textile_mills",
		"/obj/item/clothing/suit/armor/ancient/aztec_harness" = "padded_armor",
		"/obj/item/clothing/suit/armor/ancient/gator_scale_armor" = "padded_armor",
		"/obj/item/clothing/suit/armor/ancient/linen" = "padded_armor",
		"/obj/item/clothing/suit/armor/chitin" = "padded_armor",
		"/obj/item/clothing/suit/armor/medieval/bronze_chestplate" = "padded_armor",
		"/obj/item/clothing/suit/armor/medieval/leather" = "padded_armor",
		"/obj/item/clothing/suit/armor/medieval/steppe_leather" = "padded_armor",
		"/obj/item/clothing/suit/armor/samurai" = "padded_armor",
		"/obj/item/clothing/suit/armor/samurai/black" = "padded_armor",
		"/obj/item/clothing/suit/armor/samurai/blue" = "padded_armor",
		"/obj/item/clothing/suit/armor/samurai/red" = "padded_armor",
		"/obj/item/clothing/suit/b3" = "trench_warfare",
		"/obj/item/clothing/suit/gorillasuit" = "textile_mills",
		"/obj/item/clothing/suit/hairbonearmor" = "padded_armor",
		"/obj/item/clothing/suit/hawaiian" = "textile_mills",
		"/obj/item/clothing/suit/hawaiian/green" = "textile_mills",
		"/obj/item/clothing/suit/hawaiian/orange" = "textile_mills",
		"/obj/item/clothing/suit/hawaiian/purple" = "textile_mills",
		"/obj/item/clothing/suit/nbc" = "textile_mills",
		"/obj/item/clothing/suit/nbc/olive" = "textile_mills",
		"/obj/item/clothing/suit/pimpcoat" = "textile_mills",
		"/obj/item/clothing/suit/prehistoricfurcoat" = "weaving",
		"/obj/item/clothing/suit/prehistoricfurcoat/black" = "weaving",
		"/obj/item/clothing/suit/prehistoricfurcoat/brown" = "weaving",
		"/obj/item/clothing/suit/prehistoricfurcoat/grey" = "weaving",
		"/obj/item/clothing/suit/prehistoricfurcoat/white" = "weaving",
		"/obj/item/clothing/suit/storage/closechest_apron_f" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/fancy_fur_coat" = "fine_garments",
		"/obj/item/clothing/suit/storage/coat/fur" = "fine_garments",
		"/obj/item/clothing/suit/storage/coat/fur/black" = "fine_garments",
		"/obj/item/clothing/suit/storage/coat/fur/brown" = "fine_garments",
		"/obj/item/clothing/suit/storage/coat/fur/grey" = "fine_garments",
		"/obj/item/clothing/suit/storage/coat/fur/orc" = "weaving",
		"/obj/item/clothing/suit/storage/coat/fur/pink" = "weaving",
		"/obj/item/clothing/suit/storage/coat/fur/white" = "fine_garments",
		"/obj/item/clothing/suit/storage/coat/japcoat2/brown" = "fine_garments",
		"/obj/item/clothing/suit/storage/coat/monk_robes" = "tailoring",
		"/obj/item/clothing/suit/storage/coat/oldyjacket" = "synthetics",
		"/obj/item/clothing/suit/storage/coat/ruscoat/grey" = "fine_garments",
		"/obj/item/clothing/suit/storage/coat/victorian_peacoat" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/ww2/biker" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/ww2/biker/gator_jacket" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/ww2/biker/lizard_jacket" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/ww2/bomberjacketblack" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/ww2/bomberjacketbrown" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/ww2/german/civ" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/ww2/moderncoat" = "textile_mills",
		"/obj/item/clothing/suit/storage/coat/ww2/servicejacket" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/black_suit" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/blackvest" = "fine_garments",
		"/obj/item/clothing/suit/storage/jacket/bluevest" = "fine_garments",
		"/obj/item/clothing/suit/storage/jacket/bonearmor" = "padded_armor",
		"/obj/item/clothing/suit/storage/jacket/burgundy_suit" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/charcoal_suit" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/checkered_suit" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/custom/haori_jacket" = "tailoring",
		"/obj/item/clothing/suit/storage/jacket/custom/poncho" = "tailoring",
		"/obj/item/clothing/suit/storage/jacket/customcolonial" = "tailoring",
		"/obj/item/clothing/suit/storage/jacket/customcolonialcoat" = "tailoring",
		"/obj/item/clothing/suit/storage/jacket/leatherovercoat1" = "fine_garments",
		"/obj/item/clothing/suit/storage/jacket/leatherovercoat2" = "fine_garments",
		"/obj/item/clothing/suit/storage/jacket/motorist" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/navy_suit" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/olivevest" = "fine_garments",
		"/obj/item/clothing/suit/storage/jacket/piratejacket1" = "fine_garments",
		"/obj/item/clothing/suit/storage/jacket/piratejacket2" = "tailoring",
		"/obj/item/clothing/suit/storage/jacket/piratejacket3" = "fine_garments",
		"/obj/item/clothing/suit/storage/jacket/piratejacket4" = "fine_garments",
		"/obj/item/clothing/suit/storage/jacket/piratejacket5" = "tailoring",
		"/obj/item/clothing/suit/storage/jacket/plaguedoctor" = "tailoring",
		"/obj/item/clothing/suit/storage/jacket/punk" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/really_black_suit" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/regal" = "tailoring",
		"/obj/item/clothing/suit/storage/jacket/steppe_shaman" = "weaving",
		"/obj/item/clothing/suit/storage/jacket/surgeon" = "anesthetic_surgery",
		"/obj/item/clothing/suit/storage/jacket/texan" = "textile_mills",
		"/obj/item/clothing/suit/storage/jacket/vict_tailcoat" = "textile_mills",
		"/obj/item/clothing/suit/storage/openchest_apron_f" = "textile_mills",
		"/obj/item/clothing/suit/zulu_mbata" = "weaving",
		"/obj/item/clothing/under/ainu" = "weaving",
		"/obj/item/clothing/under/ainu2" = "weaving",
		"/obj/item/clothing/under/artisan" = "tailoring",
		"/obj/item/clothing/under/artisan/dark" = "tailoring",
		"/obj/item/clothing/under/artisan/light" = "tailoring",
		"/obj/item/clothing/under/aztec_loincloth" = "weaving",
		"/obj/item/clothing/under/blackdress" = "fine_garments",
		"/obj/item/clothing/under/blackdress/short" = "fine_garments",
		"/obj/item/clothing/under/celtic_long_braccae" = "weaving",
		"/obj/item/clothing/under/celtic_short_braccae" = "weaving",
		"/obj/item/clothing/under/cheongsam" = "fine_garments",
		"/obj/item/clothing/under/christian_priest" = "fine_garments",
		"/obj/item/clothing/under/civ1" = "tailoring",
		"/obj/item/clothing/under/civ2" = "fine_garments",
		"/obj/item/clothing/under/civ3" = "fine_garments",
		"/obj/item/clothing/under/civ4" = "fine_garments",
		"/obj/item/clothing/under/civ5" = "fine_garments",
		"/obj/item/clothing/under/civ6" = "fine_garments",
		"/obj/item/clothing/under/civf1" = "fine_garments",
		"/obj/item/clothing/under/civf2" = "fine_garments",
		"/obj/item/clothing/under/civf3" = "fine_garments",
		"/obj/item/clothing/under/civfg" = "fine_garments",
		"/obj/item/clothing/under/civfr" = "fine_garments",
		"/obj/item/clothing/under/conquistador" = "tailoring",
		"/obj/item/clothing/under/constable" = "textile_mills",
		"/obj/item/clothing/under/count_outfit" = "fine_garments",
		"/obj/item/clothing/under/crinoline_dress" = "fine_garments",
		"/obj/item/clothing/under/custom/arabictunic" = "tailoring",
		"/obj/item/clothing/under/custom/celtic" = "weaving",
		"/obj/item/clothing/under/custom/roman" = "weaving",
		"/obj/item/clothing/under/custom/shendyt" = "weaving",
		"/obj/item/clothing/under/custom/spartan" = "weaving",
		"/obj/item/clothing/under/custom/stola" = "weaving",
		"/obj/item/clothing/under/custom/toga" = "weaving",
		"/obj/item/clothing/under/custom/tunic" = "fine_garments",
		"/obj/item/clothing/under/customdress" = "fine_garments",
		"/obj/item/clothing/under/customdress2" = "fine_garments",
		"/obj/item/clothing/under/custompontifical" = "fine_garments",
		"/obj/item/clothing/under/custompyjamas" = "fine_garments",
		"/obj/item/clothing/under/customren" = "tailoring",
		"/obj/item/clothing/under/customtribalrobe" = "weaving",
		"/obj/item/clothing/under/customuniform" = "textile_mills",
		"/obj/item/clothing/under/customuniform/baggy" = "textile_mills",
		"/obj/item/clothing/under/customuniform/colonial" = "fine_garments",
		"/obj/item/clothing/under/customuniform/colonial/short" = "tailoring",
		"/obj/item/clothing/under/customuniform/short" = "textile_mills",
		"/obj/item/clothing/under/customuniform_modern" = "textile_mills",
		"/obj/item/clothing/under/customvicuniform" = "textile_mills",
		"/obj/item/clothing/under/debutante/blue" = "fine_garments",
		"/obj/item/clothing/under/debutante/orange" = "fine_garments",
		"/obj/item/clothing/under/debutante/purple" = "fine_garments",
		"/obj/item/clothing/under/debutante/red" = "fine_garments",
		"/obj/item/clothing/under/debutante/yellow" = "fine_garments",
		"/obj/item/clothing/under/farmer_outfit" = "textile_mills",
		"/obj/item/clothing/under/gatorpants" = "textile_mills",
		"/obj/item/clothing/under/halfhuipil" = "weaving",
		"/obj/item/clothing/under/hanfu" = "tailoring",
		"/obj/item/clothing/under/hanfu/green" = "tailoring",
		"/obj/item/clothing/under/hanfu/light" = "tailoring",
		"/obj/item/clothing/under/haori" = "tailoring",
		"/obj/item/clothing/under/haori/blue" = "tailoring",
		"/obj/item/clothing/under/haori/red" = "tailoring",
		"/obj/item/clothing/under/huipil" = "weaving",
		"/obj/item/clothing/under/indian1" = "weaving",
		"/obj/item/clothing/under/indian2" = "weaving",
		"/obj/item/clothing/under/indian3" = "weaving",
		"/obj/item/clothing/under/indianchief" = "fine_garments",
		"/obj/item/clothing/under/indianchief/pygmy" = "fine_garments",
		"/obj/item/clothing/under/indianhuge" = "weaving",
		"/obj/item/clothing/under/indianshaman" = "fine_garments",
		"/obj/item/clothing/under/indianshaman/pygmy" = "fine_garments",
		"/obj/item/clothing/under/industrial1" = "fine_garments",
		"/obj/item/clothing/under/industrial2" = "fine_garments",
		"/obj/item/clothing/under/industrial3" = "fine_garments",
		"/obj/item/clothing/under/industrial4" = "textile_mills",
		"/obj/item/clothing/under/industrial5" = "textile_mills",
		"/obj/item/clothing/under/kimono" = "weaving",
		"/obj/item/clothing/under/landschneckt" = "tailoring",
		"/obj/item/clothing/under/landschneckt/blue" = "tailoring",
		"/obj/item/clothing/under/landschneckt/red" = "tailoring",
		"/obj/item/clothing/under/leaves_skirt" = "weaving",
		"/obj/item/clothing/under/leaves_skirt/au_naturel" = "weaving",
		"/obj/item/clothing/under/leaves_skirt/au_naturel/eve" = "weaving",
		"/obj/item/clothing/under/leaves_skirt/long" = "weaving",
		"/obj/item/clothing/under/lederhosen" = "fine_garments",
		"/obj/item/clothing/under/lizardpants" = "textile_mills",
		"/obj/item/clothing/under/loincotton" = "weaving",
		"/obj/item/clothing/under/loinleather" = "weaving",
		"/obj/item/clothing/under/mayan_loincloth" = "weaving",
		"/obj/item/clothing/under/mechanic_outfit" = "textile_mills",
		"/obj/item/clothing/under/medieval/arab1" = "tailoring",
		"/obj/item/clothing/under/medieval/arab2" = "tailoring",
		"/obj/item/clothing/under/medieval/beggar_clothing" = "tailoring",
		"/obj/item/clothing/under/medieval/emirate" = "tailoring",
		"/obj/item/clothing/under/medieval/kilt" = "fine_garments",
		"/obj/item/clothing/under/medieval/steppe_tunic" = "weaving",
		"/obj/item/clothing/under/merchant_suit" = "fine_garments",
		"/obj/item/clothing/under/modern1" = "textile_mills",
		"/obj/item/clothing/under/modern2" = "textile_mills",
		"/obj/item/clothing/under/modern3" = "textile_mills",
		"/obj/item/clothing/under/modern4" = "textile_mills",
		"/obj/item/clothing/under/motorist" = "textile_mills",
		"/obj/item/clothing/under/nightingale" = "fine_garments",
		"/obj/item/clothing/under/nun" = "fine_garments",
		"/obj/item/clothing/under/pharaoh" = "weaving",
		"/obj/item/clothing/under/pharaoh2" = "weaving",
		"/obj/item/clothing/under/pilgrim" = "fine_garments",
		"/obj/item/clothing/under/pirate1" = "tailoring",
		"/obj/item/clothing/under/pirate2" = "tailoring",
		"/obj/item/clothing/under/pirate3" = "tailoring",
		"/obj/item/clothing/under/punk" = "textile_mills",
		"/obj/item/clothing/under/pygmyhuge" = "weaving",
		"/obj/item/clothing/under/pygmyshaman" = "fine_garments",
		"/obj/item/clothing/under/renaissance" = "tailoring",
		"/obj/item/clothing/under/renaissance/doge" = "tailoring",
		"/obj/item/clothing/under/renaissance_pontifical" = "tailoring",
		"/obj/item/clothing/under/saloondress" = "fine_garments",
		"/obj/item/clothing/under/sari/blue" = "tailoring",
		"/obj/item/clothing/under/sari/red" = "tailoring",
		"/obj/item/clothing/under/sundress" = "textile_mills",
		"/obj/item/clothing/under/sundress/blue" = "textile_mills",
		"/obj/item/clothing/under/sundress/orange" = "textile_mills",
		"/obj/item/clothing/under/sundress/purple" = "textile_mills",
		"/obj/item/clothing/under/sundress/red" = "textile_mills",
		"/obj/item/clothing/under/texan" = "textile_mills",
		"/obj/item/clothing/under/tradwife" = "textile_mills",
		"/obj/item/clothing/under/tradwife/orange" = "textile_mills",
		"/obj/item/clothing/under/tradwife/purple" = "textile_mills",
		"/obj/item/clothing/under/tradwife/red" = "textile_mills",
		"/obj/item/clothing/under/tradwife/yellow" = "textile_mills",
		"/obj/item/clothing/under/traffic_police" = "textile_mills",
		"/obj/item/clothing/under/victorian_dress" = "textile_mills",
		"/obj/item/clothing/under/victorian_prim" = "textile_mills",
		"/obj/item/clothing/under/victorian_vest" = "textile_mills",
		"/obj/item/clothing/under/victorian_vest/redshirt" = "textile_mills",
		"/obj/item/clothing/under/victorian_vest/redvest" = "textile_mills",
		"/obj/item/clothing/under/waistcoat" = "textile_mills",
		"/obj/item/clothing/under/wedding" = "fine_garments",
		"/obj/item/clothing/under/zulu_slene" = "weaving",
		"/obj/item/conveyor_construct" = "paved_infrastructure",
		"/obj/item/conveyor_switch_construct" = "paved_infrastructure",
		"/obj/item/flagmaker" = "herbalism",
		"/obj/item/flashlight/lantern" = "roads",
		"/obj/item/flashlight/lantern/bronze" = "paved_infrastructure",
		"/obj/item/flashlight/lantern/copper" = "paved_infrastructure",
		"/obj/item/flashlight/tiki_torch" = "pottery_storage",
		"/obj/item/flashlight/torch" = "pottery_storage",
		"/obj/item/garrote" = "bronze_weapons",
		"/obj/item/kitchen/wood_bowl" = "pottery_storage",
		"/obj/item/lightbulb" = "paved_infrastructure",
		"/obj/item/lightbulb/tube" = "paved_infrastructure",
		"/obj/item/sail" = "weaving",
		"/obj/item/sail/wool" = "herbalism",
		"/obj/item/stack/ammopart/blunderbuss" = "gunpowder",
		"/obj/item/stack/ammopart/bullet" = "gunpowder",
		"/obj/item/stack/ammopart/casing/artillery" = "field_artillery",
		"/obj/item/stack/ammopart/casing/booster" = "rail_steam",
		"/obj/item/stack/ammopart/casing/grenade" = "factories",
		"/obj/item/stack/ammopart/casing/pistol" = "rifling",
		"/obj/item/stack/ammopart/casing/rifle" = "rifling",
		"/obj/item/stack/ammopart/casing/tank" = "field_artillery",
		"/obj/item/stack/ammopart/musketball" = "gunpowder",
		"/obj/item/stack/ammopart/musketball_pistol" = "gunpowder",
		"/obj/item/stack/ammopart/stoneball" = "bronze_weapons",
		"/obj/item/stack/ammopart/warhead" = "rail_steam",
		"/obj/item/stack/arrowhead/sandstone" = "stone_arms",
		"/obj/item/stack/arrowhead/stone" = "stone_arms",
		"/obj/item/stack/arrowhead/vial" = "stone_arms",
		"/obj/item/stack/cable_coil/blue" = "paved_infrastructure",
		"/obj/item/stack/cable_coil/cyan" = "paved_infrastructure",
		"/obj/item/stack/cable_coil/green" = "paved_infrastructure",
		"/obj/item/stack/cable_coil/orange" = "paved_infrastructure",
		"/obj/item/stack/cable_coil/pink" = "paved_infrastructure",
		"/obj/item/stack/cable_coil/red" = "paved_infrastructure",
		"/obj/item/stack/cable_coil/white" = "paved_infrastructure",
		"/obj/item/stack/cable_coil/yellow" = "paved_infrastructure",
		"/obj/item/stack/material/barbwire" = "paved_infrastructure",
		"/obj/item/stack/material/bone" = "pottery_storage",
		"/obj/item/stack/material/electronics" = "printing_currency",
		"/obj/item/stack/material/rope" = "basic_tools",
		"/obj/item/stack/material/stone" = "pottery_storage",
		"/obj/item/stack/material/stonebrick" = "imperial_architecture",
		"/obj/item/stack/material/wool" = "pottery_storage",
		"/obj/item/stack/medical/advanced/bruise_pack" = "herbalism",
		"/obj/item/stack/medical/advanced/ointment" = "herbalism",
		"/obj/item/stack/medical/bruise_pack/bint" = "herbalism",
		"/obj/item/stack/medical/bruise_pack/bint/leather" = "herbalism",
		"/obj/item/stack/medical/splint" = "herbalism",
		"/obj/item/stack/money/coppercoin" = "pottery_storage",
		"/obj/item/stack/money/goldcoin" = "pottery_storage",
		"/obj/item/stack/money/silvercoin" = "pottery_storage",
		"/obj/item/trombone" = "workshops",
		"/obj/item/vehicleparts/frame/bike" = "automobiles",
		"/obj/item/vehicleparts/frame/boat" = "carts",
		"/obj/item/vehicleparts/frame/boat/rhib" = "automobiles",
		"/obj/item/violin" = "printing_currency",
		"/obj/item/weapon/analyser" = "digital_computing",
		"/obj/item/weapon/attachment/bayonet" = "bayonets",
		"/obj/item/weapon/attachment/scope/adjustable/binoculars" = "basic_furniture",
		"/obj/item/weapon/barrier/sandbag/empty" = "fortifications",
		"/obj/item/weapon/beartrap" = "bayonets",
		"/obj/item/weapon/bedroll" = "weaving",
		"/obj/item/weapon/bedsheet" = "basic_furniture",
		"/obj/item/weapon/bedsheet/blue" = "basic_furniture",
		"/obj/item/weapon/bedsheet/brown" = "basic_furniture",
		"/obj/item/weapon/bedsheet/medical" = "herbalism",
		"/obj/item/weapon/bedsheet/red" = "basic_furniture",
		"/obj/item/weapon/berriesgatherer" = "basic_tools",
		"/obj/item/weapon/book" = "printing_currency",
		"/obj/item/weapon/book/holybook" = "printing_currency",
		"/obj/item/weapon/book/language_book" = "printing_currency",
		"/obj/item/weapon/book/research" = "pottery_storage",
		"/obj/item/weapon/can" = "printing_currency",
		"/obj/item/weapon/can/large" = "printing_currency",
		"/obj/item/weapon/can/small" = "printing_currency",
		"/obj/item/weapon/cane" = "basic_tools",
		"/obj/item/weapon/chisel" = "basic_tools",
		"/obj/item/weapon/chisel/metal" = "basic_tools",
		"/obj/item/weapon/clay/advclaybricks" = "medieval_construction",
		"/obj/item/weapon/clay/advclaybricks/cement" = "medieval_construction",
		"/obj/item/weapon/clay/bigclaypot" = "pottery_storage",
		"/obj/item/weapon/clay/claybowl" = "pottery_storage",
		"/obj/item/weapon/clay/claybricks" = "stone_masonry",
		"/obj/item/weapon/clay/claycup" = "pottery_storage",
		"/obj/item/weapon/clay/clayjug" = "pottery_storage",
		"/obj/item/weapon/clay/claypitcher" = "pottery_storage",
		"/obj/item/weapon/clay/claypot" = "pottery_storage",
		"/obj/item/weapon/clay/cookingpot" = "pottery_storage",
		"/obj/item/weapon/clay/largeclaypitcher" = "pottery_storage",
		"/obj/item/weapon/clay/mold" = "bronze_working",
		"/obj/item/weapon/clay/mold/arrowhead" = "pottery_storage",
		"/obj/item/weapon/clay/mold/axehead" = "stone_arms",
		"/obj/item/weapon/clay/mold/clayjug" = "pottery_storage",
		"/obj/item/weapon/clay/mold/claypot" = "pottery_storage",
		"/obj/item/weapon/clay/mold/knife" = "stone_arms",
		"/obj/item/weapon/clay/mold/pickaxe" = "stone_arms",
		"/obj/item/weapon/clay/mold/shovel" = "basic_tools",
		"/obj/item/weapon/clay/mold/spearhead" = "stone_arms",
		"/obj/item/weapon/clay/mold/sword" = "stone_arms",
		"/obj/item/weapon/clay/roofing" = "stone_masonry",
		"/obj/item/weapon/clay/roofing/black" = "stone_masonry",
		"/obj/item/weapon/clay/roofing/blue" = "stone_masonry",
		"/obj/item/weapon/clay/roofing/kerawa" = "stone_masonry",
		"/obj/item/weapon/clay/smallclaypot" = "pottery_storage",
		"/obj/item/weapon/clay/vase" = "pottery_storage",
		"/obj/item/weapon/clay/verysmallclaypot" = "pottery_storage",
		"/obj/item/weapon/clay/winecup" = "pottery_storage",
		"/obj/item/weapon/clipboard" = "assembly_line",
		"/obj/item/weapon/compass" = "pottery_storage",
		"/obj/item/weapon/covers" = "stone_masonry",
		"/obj/item/weapon/covers/ship" = "carts",
		"/obj/item/weapon/deck/cards" = "printing_currency",
		"/obj/item/weapon/dice" = "machined_tools",
		"/obj/item/weapon/dice/d00" = "machined_tools",
		"/obj/item/weapon/dice/d10" = "machined_tools",
		"/obj/item/weapon/dice/d12" = "machined_tools",
		"/obj/item/weapon/dice/d2" = "machined_tools",
		"/obj/item/weapon/dice/d20" = "machined_tools",
		"/obj/item/weapon/dice/d4" = "machined_tools",
		"/obj/item/weapon/dice/d8" = "machined_tools",
		"/obj/item/weapon/doctor_handbook" = "printing_currency",
		"/obj/item/weapon/dummy_armor" = "padded_armor",
		"/obj/item/weapon/enginemaker" = "factories",
		"/obj/item/weapon/fishing" = "basic_tools",
		"/obj/item/weapon/fishing/modern" = "machined_tools",
		"/obj/item/weapon/fishing/net" = "basic_tools",
		"/obj/item/weapon/flame/lighter/random" = "assembly_line",
		"/obj/item/weapon/flame/lighter/zippo" = "assembly_line",
		"/obj/item/weapon/folder" = "factories",
		"/obj/item/weapon/folder/red" = "factories",
		"/obj/item/weapon/folder/yellow" = "factories",
		"/obj/item/weapon/geiger_counter" = "factories",
		"/obj/item/weapon/globe" = "printing_currency",
		"/obj/item/weapon/goldsceptre" = "pottery_storage",
		"/obj/item/weapon/gongmallet" = "pottery_storage",
		"/obj/item/weapon/grenade/dynamite" = "bayonets",
		"/obj/item/weapon/gun/projectile/ancient/arquebus" = "gunpowder",
		"/obj/item/weapon/gun/projectile/ancient/firelance" = "gunpowder",
		"/obj/item/weapon/gun/projectile/ancient/handcannon" = "gunpowder",
		"/obj/item/weapon/gun/projectile/ancient/matchlock" = "gunpowder",
		"/obj/item/weapon/gun/projectile/ancient/tanegashima" = "gunpowder",
		"/obj/item/weapon/gun/projectile/bow" = "archery",
		"/obj/item/weapon/gun/projectile/bow/compoundbow" = "crossbows",
		"/obj/item/weapon/gun/projectile/bow/crossbow" = "crossbows",
		"/obj/item/weapon/gun/projectile/bow/longbow" = "crossbows",
		"/obj/item/weapon/gun/projectile/bow/shortbow" = "archery",
		"/obj/item/weapon/gun/projectile/bow/sling" = "archery",
		"/obj/item/weapon/gun/projectile/dartgun/blowgun" = "archery",
		"/obj/item/weapon/gun_cleaning_kit" = "gunpowder",
		"/obj/item/weapon/hammer" = "stone_arms",
		"/obj/item/weapon/hammer/modern" = "bayonets",
		"/obj/item/weapon/handbell" = "pottery_storage",
		"/obj/item/weapon/handcuffs" = "bayonets",
		"/obj/item/weapon/handcuffs/rope" = "stone_arms",
		"/obj/item/weapon/horn" = "pottery_storage",
		"/obj/item/weapon/key" = "pottery_storage",
		"/obj/item/weapon/leash" = "pottery_storage",
		"/obj/item/weapon/macuahuitl" = "stone_arms",
		"/obj/item/weapon/matchbox" = "printing_currency",
		"/obj/item/weapon/material/ashtray" = "printing_currency",
		"/obj/item/weapon/material/ashtray/bronze" = "printing_currency",
		"/obj/item/weapon/material/ashtray/glass" = "factories",
		"/obj/item/weapon/material/ashtray/marble" = "printing_currency",
		"/obj/item/weapon/material/ashtray/stone" = "printing_currency",
		"/obj/item/weapon/material/bust" = "printing_currency",
		"/obj/item/weapon/material/fancycane" = "iron_tools",
		"/obj/item/weapon/material/handle" = "basic_tools",
		"/obj/item/weapon/material/hatchet/bone_battleaxe" = "stone_arms",
		"/obj/item/weapon/material/hatchet/tribal" = "basic_tools",
		"/obj/item/weapon/material/hatchet/tribal/bone" = "basic_tools",
		"/obj/item/weapon/material/hippocratic" = "printing_currency",
		"/obj/item/weapon/material/kitchen/rollingpin" = "basic_tools",
		"/obj/item/weapon/material/kitchen/utensil/chopsticks" = "pottery_storage",
		"/obj/item/weapon/material/kitchen/utensil/knife/bone" = "stone_arms",
		"/obj/item/weapon/material/kitchen/utensil/knife/razorblade" = "stone_arms",
		"/obj/item/weapon/material/kitchen/utensil/knife/shank" = "bronze_weapons",
		"/obj/item/weapon/material/kitchen/utensil/knife/shank/glass" = "bayonets",
		"/obj/item/weapon/material/kitchen/utensil/knife/shank/iron" = "bronze_weapons",
		"/obj/item/weapon/material/kitchen/utensil/knife/wood" = "stone_arms",
		"/obj/item/weapon/material/marx" = "assembly_line",
		"/obj/item/weapon/material/pickaxe/bone" = "stone_arms",
		"/obj/item/weapon/material/pickaxe/jackhammer" = "bayonets",
		"/obj/item/weapon/material/pickaxe/stone" = "stone_arms",
		"/obj/item/weapon/material/pilum" = "stone_arms",
		"/obj/item/weapon/material/pitchfork" = "pottery_storage",
		"/obj/item/weapon/material/quarterstaff" = "pottery_storage",
		"/obj/item/weapon/material/shovel/bone" = "basic_tools",
		"/obj/item/weapon/material/shovel/trench" = "padded_armor",
		"/obj/item/weapon/material/spear" = "stone_arms",
		"/obj/item/weapon/material/spear/dory" = "stone_arms",
		"/obj/item/weapon/material/spear/sarissa" = "stone_arms",
		"/obj/item/weapon/material/sword/training" = "stone_arms",
		"/obj/item/weapon/material/sword/training/bamboo" = "stone_arms",
		"/obj/item/weapon/material/thrown/kunai_normal" = "bronze_weapons",
		"/obj/item/weapon/material/thrown/star" = "bronze_weapons",
		"/obj/item/weapon/material/thrown/tomahawk" = "stone_arms",
		"/obj/item/weapon/material/trowel" = "pottery_storage",
		"/obj/item/weapon/melee/classic_baton" = "bayonets",
		"/obj/item/weapon/melee/classic_baton/club" = "stone_arms",
		"/obj/item/weapon/melee/classic_baton/whip" = "bronze_weapons",
		"/obj/item/weapon/mop" = "basic_tools",
		"/obj/item/weapon/paper" = "printing_currency",
		"/obj/item/weapon/paper/official" = "printing_currency",
		"/obj/item/weapon/paper_bin/empty" = "printing_currency",
		"/obj/item/weapon/pen" = "printing_currency",
		"/obj/item/weapon/plough" = "basic_tools",
		"/obj/item/weapon/plough/iron" = "basic_tools",
		"/obj/item/weapon/poster/faction/lead" = "printing_currency",
		"/obj/item/weapon/poster/faction/mil1" = "printing_currency",
		"/obj/item/weapon/poster/faction/mil2" = "printing_currency",
		"/obj/item/weapon/poster/faction/work" = "printing_currency",
		"/obj/item/weapon/poster/religious" = "printing_currency",
		"/obj/item/weapon/prosthesis/pegleg" = "herbalism",
		"/obj/item/weapon/prosthesis/woodfoot" = "herbalism",
		"/obj/item/weapon/punji_sticks" = "pottery_storage",
		"/obj/item/weapon/radio" = "manufactured_furniture",
		"/obj/item/weapon/radio/walkietalkie" = "assembly_line",
		"/obj/item/weapon/reagent_containers/blood/empty" = "apothecary",
		"/obj/item/weapon/reagent_containers/dropper" = "printing_currency",
		"/obj/item/weapon/reagent_containers/food/drinks/bottle/large" = "printing_currency",
		"/obj/item/weapon/reagent_containers/food/drinks/bottle/small" = "printing_currency",
		"/obj/item/weapon/reagent_containers/food/drinks/bottle/small/custom/beer" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/food/drinks/bottle/small/custom/fancybeer" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/food/drinks/britmug" = "factories",
		"/obj/item/weapon/reagent_containers/food/drinks/drinkingglass" = "printing_currency",
		"/obj/item/weapon/reagent_containers/food/drinks/drinkingglass/beermug" = "printing_currency",
		"/obj/item/weapon/reagent_containers/food/drinks/drinkingglass/custom/fastfoodcup" = "assembly_line",
		"/obj/item/weapon/reagent_containers/food/drinks/drinkingglass/tribalpot" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/food/drinks/drinkingglass/waterskin" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/food/drinks/drinkingglass/wood" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/food/drinks/gunpowder" = "iron_smithing",
		"/obj/item/weapon/reagent_containers/food/drinks/plastic/carton" = "factories",
		"/obj/item/weapon/reagent_containers/food/drinks/plastic/cola" = "assembly_line",
		"/obj/item/weapon/reagent_containers/food/drinks/plastic/condiment" = "assembly_line",
		"/obj/item/weapon/reagent_containers/food/drinks/plastic/gallonjug" = "assembly_line",
		"/obj/item/weapon/reagent_containers/food/drinks/plastic/sodacan" = "assembly_line",
		"/obj/item/weapon/reagent_containers/food/drinks/plastic/tallcan" = "assembly_line",
		"/obj/item/weapon/reagent_containers/food/drinks/shaker" = "assembly_line",
		"/obj/item/weapon/reagent_containers/food/drinks/sillycup" = "factories",
		"/obj/item/weapon/reagent_containers/food/drinks/tea/empty" = "printing_currency",
		"/obj/item/weapon/reagent_containers/food/drinks/teapot" = "printing_currency",
		"/obj/item/weapon/reagent_containers/food/snacks/leaf_salad" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/glass/barrel" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/glass/barrel/fueltank" = "rail_steam",
		"/obj/item/weapon/reagent_containers/glass/barrel/fueltank/bike" = "rail_steam",
		"/obj/item/weapon/reagent_containers/glass/barrel/fueltank/bike25" = "rail_steam",
		"/obj/item/weapon/reagent_containers/glass/barrel/fueltank/bike75" = "rail_steam",
		"/obj/item/weapon/reagent_containers/glass/barrel/fueltank/small" = "rail_steam",
		"/obj/item/weapon/reagent_containers/glass/barrel/fueltank/smalltank" = "rail_steam",
		"/obj/item/weapon/reagent_containers/glass/barrel/fueltank/tank" = "rail_steam",
		"/obj/item/weapon/reagent_containers/glass/barrel/jerrycan" = "factories",
		"/obj/item/weapon/reagent_containers/glass/barrel/modern" = "factories",
		"/obj/item/weapon/reagent_containers/glass/beaker" = "factories",
		"/obj/item/weapon/reagent_containers/glass/beaker/large" = "factories",
		"/obj/item/weapon/reagent_containers/glass/beaker/vial" = "printing_currency",
		"/obj/item/weapon/reagent_containers/glass/bucket" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/glass/extraction_kit" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/glass/fire_extinguisher/empty" = "printing_currency",
		"/obj/item/weapon/reagent_containers/glass/rag" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/glass/small_pot" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/glass/small_pot/copper_large" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/glass/small_pot/copper_small" = "pottery_storage",
		"/obj/item/weapon/reagent_containers/glass/small_pot/hangou" = "printing_currency",
		"/obj/item/weapon/reagent_containers/pill/cocaine" = "apothecary",
		"/obj/item/weapon/reagent_containers/pill/opium" = "herbalism",
		"/obj/item/weapon/reagent_containers/syringe" = "field_surgery",
		"/obj/item/weapon/researchkit" = "pottery_storage",
		"/obj/item/weapon/roofbuilder" = "stone_masonry",
		"/obj/item/weapon/roofbuilder/concrete" = "imperial_architecture",
		"/obj/item/weapon/roofbuilder/glass" = "imperial_architecture",
		"/obj/item/weapon/roofbuilder/leaves" = "stone_masonry",
		"/obj/item/weapon/roofbuilder/mayan" = "stone_masonry",
		"/obj/item/weapon/roofbuilder/palm" = "stone_masonry",
		"/obj/item/weapon/roofbuilder/sandstone" = "stone_masonry",
		"/obj/item/weapon/shears" = "pottery_storage",
		"/obj/item/weapon/shield" = "padded_armor",
		"/obj/item/weapon/shield/chimalli" = "padded_armor",
		"/obj/item/weapon/shield/chitin" = "padded_armor",
		"/obj/item/weapon/shield/chitin/large" = "padded_armor",
		"/obj/item/weapon/shield/nguni_shield" = "padded_armor",
		"/obj/item/weapon/siegeladder" = "siege_engines",
		"/obj/item/weapon/siegeladder/metal" = "field_artillery",
		"/obj/item/weapon/stamp/approved" = "printing_currency",
		"/obj/item/weapon/stamp/captain" = "printing_currency",
		"/obj/item/weapon/stamp/ce" = "printing_currency",
		"/obj/item/weapon/stamp/clown" = "printing_currency",
		"/obj/item/weapon/stamp/denied" = "printing_currency",
		"/obj/item/weapon/stamp/hop" = "printing_currency",
		"/obj/item/weapon/stamp/hos" = "printing_currency",
		"/obj/item/weapon/stamp/internalaffairs" = "printing_currency",
		"/obj/item/weapon/stamp/mail" = "printing_currency",
		"/obj/item/weapon/starterjar" = "pottery_storage",
		"/obj/item/weapon/storage/backpack" = "pottery_storage",
		"/obj/item/weapon/storage/backpack/duffel" = "textile_mills",
		"/obj/item/weapon/storage/backpack/quiver" = "archery",
		"/obj/item/weapon/storage/backpack/rucksack" = "pottery_storage",
		"/obj/item/weapon/storage/backpack/satchel" = "textile_mills",
		"/obj/item/weapon/storage/backpack/satchel/gator_satchel" = "textile_mills",
		"/obj/item/weapon/storage/backpack/satchel/lizard_satchel" = "textile_mills",
		"/obj/item/weapon/storage/bag/cash" = "fine_garments",
		"/obj/item/weapon/storage/bag/plasticbag" = "textile_mills",
		"/obj/item/weapon/storage/bag/trash" = "textile_mills",
		"/obj/item/weapon/storage/belt/gator_belt" = "printing_currency",
		"/obj/item/weapon/storage/belt/keychain" = "pottery_storage",
		"/obj/item/weapon/storage/belt/leather" = "weaving",
		"/obj/item/weapon/storage/belt/lizard_belt" = "printing_currency",
		"/obj/item/weapon/storage/briefcase" = "fine_garments",
		"/obj/item/weapon/storage/envelope" = "printing_currency",
		"/obj/item/weapon/storage/fancy/cigar" = "printing_currency",
		"/obj/item/weapon/storage/fancy/cigarettes" = "printing_currency",
		"/obj/item/weapon/storage/firstaid/surgery_empty" = "field_surgery",
		"/obj/item/weapon/storage/foodbox" = "printing_currency",
		"/obj/item/weapon/storage/foodbox/chippack" = "assembly_line",
		"/obj/item/weapon/storage/ore_collector" = "bronze_working",
		"/obj/item/weapon/storage/photo_album" = "printing_currency",
		"/obj/item/weapon/storage/produce_basket" = "pottery_storage",
		"/obj/item/weapon/storage/seed_collector" = "pottery_storage",
		"/obj/item/weapon/storage/toolbox" = "printing_currency",
		"/obj/item/weapon/storage/toolbox/blue" = "printing_currency",
		"/obj/item/weapon/storage/toolbox/yellow" = "printing_currency",
		"/obj/item/weapon/storage/ww2" = "factories",
		"/obj/item/weapon/storage/ww2/shaving_kit" = "weaving",
		"/obj/item/weapon/storage/ww2/slunch" = "assembly_line",
		"/obj/item/weapon/stucco/generic" = "pottery_storage",
		"/obj/item/weapon/stucco/roman" = "pottery_storage",
		"/obj/item/weapon/surgery/bone_saw" = "field_surgery",
		"/obj/item/weapon/surgery/bone_saw/bronze" = "field_surgery",
		"/obj/item/weapon/surgery/bonesetter" = "field_surgery",
		"/obj/item/weapon/surgery/bonesetter/bronze" = "field_surgery",
		"/obj/item/weapon/surgery/cautery" = "field_surgery",
		"/obj/item/weapon/surgery/cautery/bronze" = "field_surgery",
		"/obj/item/weapon/surgery/hemostat" = "field_surgery",
		"/obj/item/weapon/surgery/hemostat/bronze" = "field_surgery",
		"/obj/item/weapon/surgery/retractor" = "field_surgery",
		"/obj/item/weapon/surgery/retractor/bronze" = "field_surgery",
		"/obj/item/weapon/surgery/scalpel" = "field_surgery",
		"/obj/item/weapon/surgery/scalpel/bronze" = "field_surgery",
		"/obj/item/weapon/surgery/surgicaldrill" = "surgical_theory",
		"/obj/item/weapon/swatter" = "pottery_storage",
		"/obj/item/weapon/swatter/modern" = "pottery_storage",
		"/obj/item/weapon/telephone" = "printing_currency",
		"/obj/item/weapon/telephone/mobile" = "digital_computing",
		"/obj/item/weapon/tent" = "weaving",
		"/obj/item/weapon/trafficcone" = "assembly_line",
		"/obj/item/weapon/visa" = "printing_currency",
		"/obj/item/weapon/watch/pocket" = "factories",
		"/obj/item/weapon/weldingtool" = "iron_tools",
		"/obj/item/weapon/whistle" = "printing_currency",
		"/obj/item/weapon/wirecutters" = "paved_infrastructure",
		"/obj/item/weapon/wrench" = "basic_tools",
		"/obj/structure/TV/grandfather" = "fine_furniture",
		"/obj/structure/TV/television" = "assembly_line",
		"/obj/structure/altar/iron" = "pottery_storage",
		"/obj/structure/altar/marble" = "pottery_storage",
		"/obj/structure/altar/obsidian" = "pottery_storage",
		"/obj/structure/altar/sandstone" = "pottery_storage",
		"/obj/structure/altar/stone" = "pottery_storage",
		"/obj/structure/altar/wood" = "pottery_storage",
		"/obj/structure/anvil" = "printing_currency",
		"/obj/structure/anvil/steel" = "printing_currency",
		"/obj/structure/anvil/stone" = "stone_arms",
		"/obj/structure/bakelizer" = "factories",
		"/obj/structure/banner/faction/banner_a" = "herbalism",
		"/obj/structure/banner/faction/banner_b" = "herbalism",
		"/obj/structure/banner/religious" = "herbalism",
		"/obj/structure/barbwire" = "roads",
		"/obj/structure/barricade" = "padded_armor",
		"/obj/structure/barricade/antitank" = "field_artillery",
		"/obj/structure/barricade/horizontal" = "padded_armor",
		"/obj/structure/barricade/jap" = "padded_armor",
		"/obj/structure/barricade/jap_h" = "fortifications",
		"/obj/structure/barricade/jap_h_l" = "fortifications",
		"/obj/structure/barricade/jap_h_r" = "fortifications",
		"/obj/structure/barricade/jap_v" = "fortifications",
		"/obj/structure/barricade/jap_v_b" = "fortifications",
		"/obj/structure/barricade/jap_v_t" = "fortifications",
		"/obj/structure/barricade/sandstone_h/crenelated" = "fortifications",
		"/obj/structure/barricade/sandstone_v/crenelated" = "fortifications",
		"/obj/structure/barricade/ship/aport0" = "siege_engines",
		"/obj/structure/barricade/ship/aport0/north" = "siege_engines",
		"/obj/structure/barricade/ship/blue/b9" = "padded_armor",
		"/obj/structure/barricade/ship/wall2" = "padded_armor",
		"/obj/structure/barricade/ship/wall2/doorway" = "padded_armor",
		"/obj/structure/barricade/ship/wood/a2" = "padded_armor",
		"/obj/structure/barricade/ship/wood/a6" = "padded_armor",
		"/obj/structure/barricade/ship/wood/a7" = "padded_armor",
		"/obj/structure/barricade/stone_h" = "fortifications",
		"/obj/structure/barricade/stone_h/crenelated" = "fortifications",
		"/obj/structure/barricade/stone_v" = "fortifications",
		"/obj/structure/barricade/stone_v/crenelated" = "fortifications",
		"/obj/structure/barricade/vertical" = "padded_armor",
		"/obj/structure/barricade/wood_pole" = "padded_armor",
		"/obj/structure/bed/chair/carseat/left" = "manufactured_furniture",
		"/obj/structure/bed/chair/carseat/right" = "manufactured_furniture",
		"/obj/structure/bed/chair/comfy/brown" = "basic_furniture",
		"/obj/structure/bed/chair/commander" = "manufactured_furniture",
		"/obj/structure/bed/chair/drivers" = "manufactured_furniture",
		"/obj/structure/bed/chair/drivers/car" = "automobiles",
		"/obj/structure/bed/chair/gunner" = "manufactured_furniture",
		"/obj/structure/bed/chair/loader" = "manufactured_furniture",
		"/obj/structure/bed/chair/office/dark" = "manufactured_furniture",
		"/obj/structure/bed/chair/office/light" = "manufactured_furniture",
		"/obj/structure/bed/chair/steel" = "manufactured_furniture",
		"/obj/structure/bed/chair/wheelchair" = "fine_furniture",
		"/obj/structure/bed/chair/wood" = "basic_furniture",
		"/obj/structure/bed/chair/wood/red" = "fine_furniture",
		"/obj/structure/bed/chair/wood/wings" = "fine_furniture",
		"/obj/structure/bed/psych" = "fine_furniture",
		"/obj/structure/bed/sofa" = "fine_furniture",
		"/obj/structure/bed/sofa/left" = "fine_furniture",
		"/obj/structure/bed/sofa/right" = "fine_furniture",
		"/obj/structure/bed/wood" = "basic_furniture",
		"/obj/structure/bell_stand" = "pottery_storage",
		"/obj/structure/bookcase" = "pottery_storage",
		"/obj/structure/brazier" = "basic_furniture",
		"/obj/structure/brazier/obsidian" = "basic_furniture",
		"/obj/structure/brazier/sandstone" = "basic_furniture",
		"/obj/structure/brazier/stone" = "basic_furniture",
		"/obj/structure/canner" = "printing_currency",
		"/obj/structure/cannon" = "cannon",
		"/obj/structure/cannon/modern" = "field_artillery",
		"/obj/structure/cannon/modern/tank" = "field_artillery",
		"/obj/structure/catapult" = "siege_engines",
		"/obj/structure/cell_tower" = "digital_computing",
		"/obj/structure/centrifuge" = "printing_currency",
		"/obj/structure/chem_master" = "apothecary",
		"/obj/structure/chemical_dispenser" = "printing_currency",
		"/obj/structure/closet" = "factories",
		"/obj/structure/closet/cabinet" = "tailoring",
		"/obj/structure/closet/cabinet/ceiling" = "fine_furniture",
		"/obj/structure/closet/coffin" = "basic_furniture",
		"/obj/structure/closet/coffin/generic" = "basic_furniture",
		"/obj/structure/closet/coffin/sarcophagus" = "basic_furniture",
		"/obj/structure/closet/coffin/sarcophagus/gold" = "basic_furniture",
		"/obj/structure/closet/crate" = "factories",
		"/obj/structure/closet/crate/bin" = "factories",
		"/obj/structure/closet/crate/cart/bronze" = "wagons_ships",
		"/obj/structure/closet/crate/cart/copper" = "carts",
		"/obj/structure/closet/crate/cart/steel" = "automobiles",
		"/obj/structure/closet/crate/cart/stone" = "carts",
		"/obj/structure/closet/crate/cart/wooden" = "carts",
		"/obj/structure/closet/crate/cash_register" = "assembly_line",
		"/obj/structure/closet/crate/chest" = "pottery_storage",
		"/obj/structure/closet/crate/dumpster" = "factories",
		"/obj/structure/closet/crate/empty" = "pottery_storage",
		"/obj/structure/closet/crate/empty/large" = "printing_currency",
		"/obj/structure/closet/crate/footlocker" = "printing_currency",
		"/obj/structure/closet/crate/large" = "factories",
		"/obj/structure/closet/crate/lead" = "workshops",
		"/obj/structure/closet/crate/wall_mailbox" = "imperial_architecture",
		"/obj/structure/closet/crate/wall_mailbox/wood_mailbox" = "printing_currency",
		"/obj/structure/closet/crate/ww2" = "factories",
		"/obj/structure/closet/fridge" = "pharmacology",
		"/obj/structure/compost" = "pottery_storage",
		"/obj/structure/converter/acid_bath" = "germ_theory",
		"/obj/structure/converter/retting_trough" = "pottery_storage",
		"/obj/structure/converter/tanning" = "pottery_storage",
		"/obj/structure/cross" = "stone_arms",
		"/obj/structure/cross/tau" = "stone_arms",
		"/obj/structure/curtain" = "weaving",
		"/obj/structure/curtain/leather" = "pottery_storage",
		"/obj/structure/cutting_board" = "pottery_storage",
		"/obj/structure/dehydrator" = "pottery_storage",
		"/obj/structure/distillery" = "pottery_storage",
		"/obj/structure/drill" = "machined_tools",
		"/obj/structure/drying_rack" = "herbalism",
		"/obj/structure/engine/external/steam" = "watermills",
		"/obj/structure/filingcabinet" = "basic_furniture",
		"/obj/structure/filingcabinet/chestdrawer" = "basic_furniture",
		"/obj/structure/filingcabinet/filingcabinet" = "basic_furniture",
		"/obj/structure/fishing_cage" = "basic_tools",
		"/obj/structure/flag/pole" = "pottery_storage",
		"/obj/structure/fuelpump/n" = "paved_infrastructure",
		"/obj/structure/fuelpump/s" = "paved_infrastructure",
		"/obj/structure/fuelpump/small" = "paved_infrastructure",
		"/obj/structure/fuelpump/star" = "paved_infrastructure",
		"/obj/structure/furnace" = "stone_masonry",
		"/obj/structure/furnace/blast_furnace" = "bayonets",
		"/obj/structure/furnace/kiln" = "bronze_working",
		"/obj/structure/furnace/kiln/sandstone" = "bronze_working",
		"/obj/structure/furnace/kiln/stone" = "bronze_working",
		"/obj/structure/gallows" = "stone_arms",
		"/obj/structure/gate" = "imperial_architecture",
		"/obj/structure/gate/blast" = "reinforced_concrete",
		"/obj/structure/gate/sandstone" = "imperial_architecture",
		"/obj/structure/gatecontrol" = "imperial_architecture",
		"/obj/structure/gatecontrol/blastcontrol" = "reinforced_concrete",
		"/obj/structure/gatecontrol/sandstone" = "imperial_architecture",
		"/obj/structure/gong" = "pottery_storage",
		"/obj/structure/grille/chainlinkfence" = "reinforced_concrete",
		"/obj/structure/grille/fence" = "stone_masonry",
		"/obj/structure/grille/fence/picket" = "stone_masonry",
		"/obj/structure/grille/fence/steel_picket" = "stone_masonry",
		"/obj/structure/grille/ironfence" = "stone_masonry",
		"/obj/structure/grille/logfence" = "padded_armor",
		"/obj/structure/grille/metalsheetfence" = "reinforced_concrete",
		"/obj/structure/gunbench" = "manufactured_furniture",
		"/obj/structure/heatsource" = "bayonets",
		"/obj/structure/iv_drip" = "surgical_theory",
		"/obj/structure/lab_distillery" = "factories",
		"/obj/structure/lamp/lamp_big" = "paved_infrastructure",
		"/obj/structure/lamp/lamp_small" = "paved_infrastructure",
		"/obj/structure/lamp/lamppost_small" = "paved_infrastructure",
		"/obj/structure/loom" = "weaving",
		"/obj/structure/machinery/factory/coinsmelter" = "iron_smithing",
		"/obj/structure/meat_grinder" = "apothecary",
		"/obj/structure/mill" = "pottery_storage",
		"/obj/structure/mine_support" = "stone_masonry",
		"/obj/structure/mine_support/stone" = "stone_masonry",
		"/obj/structure/mine_support/stone/aztec" = "stone_masonry",
		"/obj/structure/mine_support/stone/aztec/marble" = "stone_masonry",
		"/obj/structure/mine_support/stone/aztec/obsidian" = "stone_masonry",
		"/obj/structure/mine_support/stone/aztec/sandstone" = "stone_masonry",
		"/obj/structure/mine_support/stone/concrete" = "imperial_architecture",
		"/obj/structure/mine_support/stone/egyptian" = "stone_masonry",
		"/obj/structure/mine_support/stone/ionic" = "imperial_architecture",
		"/obj/structure/mine_support/stone/ionic/obsidian" = "imperial_architecture",
		"/obj/structure/mine_support/stone/ionic/rock" = "imperial_architecture",
		"/obj/structure/mine_support/stone/ionic/sandstone" = "imperial_architecture",
		"/obj/structure/mine_support/stone/marble" = "stone_masonry",
		"/obj/structure/mine_support/stone/obsidian" = "stone_masonry",
		"/obj/structure/mine_support/stone/sandstone" = "stone_masonry",
		"/obj/structure/mine_support/stone/solomonic" = "imperial_architecture",
		"/obj/structure/mine_support/stone/solomonic/obsidian" = "imperial_architecture",
		"/obj/structure/mine_support/stone/solomonic/rock" = "imperial_architecture",
		"/obj/structure/mine_support/stone/solomonic/sandstone" = "imperial_architecture",
		"/obj/structure/mine_support/stone/solomonic/thick" = "imperial_architecture",
		"/obj/structure/mine_support/stone/solomonic/thick/obsidian" = "imperial_architecture",
		"/obj/structure/mine_support/stone/solomonic/thick/rock" = "imperial_architecture",
		"/obj/structure/mine_support/stone/solomonic/thick/sandstone" = "imperial_architecture",
		"/obj/structure/mirror" = "sanitation",
		"/obj/structure/money_printer" = "pottery_storage",
		"/obj/structure/noose" = "stone_arms",
		"/obj/structure/noticeboard" = "printing_currency",
		"/obj/structure/oil_deposits" = "factories",
		"/obj/structure/oilwell" = "paved_infrastructure",
		"/obj/structure/oven" = "fine_furniture",
		"/obj/structure/oven/fireplace" = "basic_furniture",
		"/obj/structure/oven/grill" = "manufactured_furniture",
		"/obj/structure/oven/woodstove" = "fine_furniture",
		"/obj/structure/phoneline" = "printing_currency",
		"/obj/structure/piano" = "printing_currency",
		"/obj/structure/pillory" = "stone_arms",
		"/obj/structure/plant_pot/clay/light" = "pottery_storage",
		"/obj/structure/plant_pot/medium_planter/clay/yellow" = "pottery_storage",
		"/obj/structure/pot" = "pottery_storage",
		"/obj/structure/practice_dummy" = "pottery_storage",
		"/obj/structure/practice_dummy/target" = "pottery_storage",
		"/obj/structure/printingpress" = "printing_currency",
		"/obj/structure/radio" = "factories",
		"/obj/structure/radio/receiver/loudspeaker" = "assembly_line",
		"/obj/structure/radio/transmitter" = "factories",
		"/obj/structure/radio/transmitter_receiver" = "assembly_line",
		"/obj/structure/rails/regular" = "wagons_ships",
		"/obj/structure/rails/regular/horizontal" = "wagons_ships",
		"/obj/structure/rails/rotate" = "wagons_ships",
		"/obj/structure/rails/split/switcher" = "wagons_ships",
		"/obj/structure/rails/split/switcher/right" = "wagons_ships",
		"/obj/structure/rails/turn" = "wagons_ships",
		"/obj/structure/reagent_dispensers/largebarrel" = "pottery_storage",
		"/obj/structure/refinery" = "factories",
		"/obj/structure/refinery/biofuel" = "factories",
		"/obj/structure/religious/angel" = "imperial_architecture",
		"/obj/structure/religious/aztec_statue" = "stone_masonry",
		"/obj/structure/religious/gargoyle" = "imperial_architecture",
		"/obj/structure/religious/gravestone" = "pottery_storage",
		"/obj/structure/religious/impaledskull" = "pottery_storage",
		"/obj/structure/religious/moai" = "pottery_storage",
		"/obj/structure/religious/moai/long" = "pottery_storage",
		"/obj/structure/religious/monument/crucero" = "imperial_architecture",
		"/obj/structure/religious/monument/cultist/cthulu" = "stone_masonry",
		"/obj/structure/religious/monument/cultist/moloch" = "imperial_architecture",
		"/obj/structure/religious/monument/cultist/outsider" = "stone_masonry",
		"/obj/structure/religious/monument/cultist/sauron" = "stone_masonry",
		"/obj/structure/religious/monument/karl_marx" = "reinforced_concrete",
		"/obj/structure/religious/monument/megalith" = "stone_masonry",
		"/obj/structure/religious/monument/monk/quangshi" = "stone_masonry",
		"/obj/structure/religious/monument/obelisk" = "stone_masonry",
		"/obj/structure/religious/monument/pillar_monument" = "imperial_architecture",
		"/obj/structure/religious/monument/priesthood/saint" = "imperial_architecture",
		"/obj/structure/religious/monument/shaman/ape" = "stone_masonry",
		"/obj/structure/religious/monument/venus" = "imperial_architecture",
		"/obj/structure/religious/olmec_head" = "pottery_storage",
		"/obj/structure/religious/statue" = "stone_masonry",
		"/obj/structure/religious/tiki_statue" = "stone_masonry",
		"/obj/structure/religious/tiki_statue/small" = "stone_masonry",
		"/obj/structure/religious/totem" = "pottery_storage",
		"/obj/structure/religious/totem/sandstone" = "pottery_storage",
		"/obj/structure/religious/totem_pole" = "pottery_storage",
		"/obj/structure/religious/tribalmask" = "weaving",
		"/obj/structure/religious/woodcross1" = "printing_currency",
		"/obj/structure/religious/woodcross2" = "printing_currency",
		"/obj/structure/repair/grindstone" = "pottery_storage",
		"/obj/structure/repair/gun" = "gunpowder",
		"/obj/structure/repair/workbench" = "padded_armor",
		"/obj/structure/researchdesk" = "basic_furniture",
		"/obj/structure/researchdesk/chad" = "basic_furniture",
		"/obj/structure/roof_support" = "stone_masonry",
		"/obj/structure/roof_support/bamboo" = "stone_masonry",
		"/obj/structure/roof_support/nordic" = "stone_masonry",
		"/obj/structure/salting_container" = "pottery_storage",
		"/obj/structure/sawmill" = "pottery_storage",
		"/obj/structure/sawmill/large" = "pottery_storage",
		"/obj/structure/sawmill/powered" = "printing_currency",
		"/obj/structure/shellrack" = "bayonets",
		"/obj/structure/shopping_cart" = "automobiles",
		"/obj/structure/shower" = "sanitation",
		"/obj/structure/shower/bathtub/big/bronze" = "sanitation",
		"/obj/structure/shower/bathtub/big/copper" = "hygiene",
		"/obj/structure/shower/bathtub/big/steel" = "germ_theory",
		"/obj/structure/shower/bathtub/big/stone" = "hygiene",
		"/obj/structure/shower/bathtub/big/wooden" = "hygiene",
		"/obj/structure/shower/bathtub/bronze" = "hygiene",
		"/obj/structure/shower/bathtub/copper" = "hygiene",
		"/obj/structure/shower/bathtub/steel" = "germ_theory",
		"/obj/structure/shower/bathtub/stone" = "hygiene",
		"/obj/structure/shower/bathtub/wooden" = "hygiene",
		"/obj/structure/sign/clock" = "fine_furniture",
		"/obj/structure/sign/custom" = "stone_masonry",
		"/obj/structure/sign/custom/golden" = "imperial_architecture",
		"/obj/structure/sign/custom/metallic" = "imperial_architecture",
		"/obj/structure/sign/custom/plaque" = "stone_masonry",
		"/obj/structure/sign/painting1" = "imperial_architecture",
		"/obj/structure/sign/painting10" = "imperial_architecture",
		"/obj/structure/sign/painting11" = "medieval_construction",
		"/obj/structure/sign/painting12" = "medieval_construction",
		"/obj/structure/sign/painting13" = "medieval_construction",
		"/obj/structure/sign/painting2" = "imperial_architecture",
		"/obj/structure/sign/painting3" = "imperial_architecture",
		"/obj/structure/sign/painting4" = "imperial_architecture",
		"/obj/structure/sign/painting5" = "imperial_architecture",
		"/obj/structure/sign/painting6" = "imperial_architecture",
		"/obj/structure/sign/painting7" = "imperial_architecture",
		"/obj/structure/sign/painting8" = "imperial_architecture",
		"/obj/structure/sign/painting9" = "imperial_architecture",
		"/obj/structure/sign/radiation" = "reinforced_concrete",
		"/obj/structure/sign/signpost" = "stone_masonry",
		"/obj/structure/sign/traffic/crossing" = "reinforced_concrete",
		"/obj/structure/sign/traffic/noentry" = "reinforced_concrete",
		"/obj/structure/sign/traffic/stop" = "reinforced_concrete",
		"/obj/structure/sign/traffic/yeld" = "reinforced_concrete",
		"/obj/structure/simple_door/fence" = "stone_masonry",
		"/obj/structure/simple_door/fence/picket" = "stone_masonry",
		"/obj/structure/simple_door/key_door/anyone" = "stone_masonry",
		"/obj/structure/simple_door/key_door/anyone/aztec" = "stone_masonry",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/bamboo" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/bronze" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/copper" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/gold" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/iron" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/lead" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/marble" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/sandstone" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/silver" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/steel" = "workshops",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/stone" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/tin" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/doubledoor/wood" = "pottery_storage",
		"/obj/structure/simple_door/key_door/anyone/nordic" = "stone_masonry",
		"/obj/structure/simple_door/key_door/anyone/roman" = "stone_masonry",
		"/obj/structure/simple_door/key_door/anyone/rustic" = "stone_masonry",
		"/obj/structure/simple_door/key_door/anyone/singledoor/housedoor" = "imperial_architecture",
		"/obj/structure/simple_door/key_door/anyone/singledoor/privacy" = "imperial_architecture",
		"/obj/structure/simple_door/key_door/anyone/wood" = "stone_masonry",
		"/obj/structure/simple_door/key_door/anyone/wood/ship" = "carts",
		"/obj/structure/simple_door/key_door/custom" = "stone_masonry",
		"/obj/structure/simple_door/key_door/custom/jail/steeljail" = "medieval_construction",
		"/obj/structure/simple_door/key_door/custom/jail/woodjail" = "stone_masonry",
		"/obj/structure/simple_door/key_door/faction_door" = "stone_masonry",
		"/obj/structure/sink" = "sanitation",
		"/obj/structure/sink/kitchen" = "sanitation",
		"/obj/structure/sink/well" = "hygiene",
		"/obj/structure/sink/well/marble" = "hygiene",
		"/obj/structure/sink/well/sandstone" = "hygiene",
		"/obj/structure/stockmarket" = "pottery_storage",
		"/obj/structure/supplier" = "pottery_storage",
		"/obj/structure/table" = "basic_furniture",
		"/obj/structure/table/fancy" = "fine_furniture",
		"/obj/structure/table/modern/retable" = "manufactured_furniture",
		"/obj/structure/table/modern/table" = "fine_furniture",
		"/obj/structure/table/rack" = "basic_furniture",
		"/obj/structure/table/rack/coatrack" = "fine_garments",
		"/obj/structure/table/rack/shelf" = "fine_furniture",
		"/obj/structure/table/wood" = "basic_furniture",
		"/obj/structure/table/wood/poker" = "fine_furniture",
		"/obj/structure/telegraph" = "factories",
		"/obj/structure/teleprinter" = "factories",
		"/obj/structure/toilet" = "sanitation",
		"/obj/structure/toilet/outhouse" = "hygiene",
		"/obj/structure/toilet/outhouse/female" = "hygiene",
		"/obj/structure/toilet/outhouse/male" = "hygiene",
		"/obj/structure/torch_stand" = "pottery_storage",
		"/obj/structure/train_lever" = "wagons_ships",
		"/obj/structure/vehicle/carriage" = "carts",
		"/obj/structure/vehicle/raft" = "pottery_storage",
		"/obj/structure/vehicleparts/axis/car" = "automobiles",
		"/obj/structure/vehicleparts/axis/heavy" = "automobiles",
		"/obj/structure/vehicleparts/axis/ship" = "carts",
		"/obj/structure/vehicleparts/axis/ship/heavy" = "carts",
		"/obj/structure/vehicleparts/frame" = "automobiles",
		"/obj/structure/vehicleparts/frame/ship" = "carts",
		"/obj/structure/vehicleparts/frame/ship/steel" = "wagons_ships",
		"/obj/structure/vehicleparts/frame/wood" = "automobiles",
		"/obj/structure/vehicleparts/movement" = "automobiles",
		"/obj/structure/vehicleparts/movement/reversed" = "rail_steam",
		"/obj/structure/vehicleparts/movement/sail" = "carts",
		"/obj/structure/vehicleparts/movement/tracks" = "field_artillery",
		"/obj/structure/vehicleparts/shipwheel" = "carts",
		"/obj/structure/vending/craftable/rifles" = "gunpowder",
		"/obj/structure/vending/craftable/rifles/wood" = "gunpowder",
		"/obj/structure/vending/sales/market_stall" = "pottery_storage",
		"/obj/structure/vending/sales/vending" = "automation",
		"/obj/structure/voting" = "pottery_storage",
		"/obj/structure/wallclock" = "manufactured_furniture",
		"/obj/structure/wallframe" = "stone_masonry",
		"/obj/structure/wallframe/bamboo" = "stone_masonry",
		"/obj/structure/window/barrier/jersey" = "modern_armor",
		"/obj/structure/window/barrier/rock" = "padded_armor",
		"/obj/structure/window/barrier/sandstone" = "padded_armor",
		"/obj/structure/window/barrier/ship/blue/bport0/south" = "padded_armor",
		"/obj/structure/window/barrier/ship/blue/bport3/south" = "padded_armor",
		"/obj/structure/window/barrier/ship/wood/port0/north" = "padded_armor",
		"/obj/structure/window/barrier/ship/wood/port2/north" = "padded_armor",
		"/obj/structure/window_frame" = "stone_masonry",
		"/obj/structure/window_frame/marble" = "stone_masonry",
		"/obj/structure/window_frame/marblefull" = "stone_masonry",
		"/obj/structure/window_frame/metal" = "imperial_architecture",
		"/obj/structure/window_frame/redsandstone" = "stone_masonry",
		"/obj/structure/window_frame/redsandstonefull" = "stone_masonry",
		"/obj/structure/window_frame/sandstone" = "stone_masonry",
		"/obj/structure/window_frame/sandstonefull" = "stone_masonry",
		"/obj/structure/window_frame/stone" = "stone_masonry",
		"/obj/structure/window_frame/stonefull" = "stone_masonry",
		"obj/covers/roads/modern" = "paved_infrastructure",
		"obj/item/weapon/gun/projectile/ancient/tanegashima" = "gunpowder",
		"obj/structure/altar/material/bamboo" = "pottery_storage",
		// Phase 3: the resource forge is gated on Workshops -- raising a
		// faction's bench cap is itself downstream of early industry.
		"/obj/structure/research_forge" = "workshops"
	)

	validate_research_tree()
	log_startup_progress("	Built research tree: [research_nodes.len] nodes, [recipe_node_requirements.len] gated recipes.")

// Sanity pass: every prereq id must resolve to a real node. Catches typos in
// the tree definition at startup instead of silently locking nodes forever.
/proc/validate_research_tree()
	for (var/node_id in research_nodes)
		var/datum/research_node/N = research_nodes[node_id]
		for (var/req in N.prereqs)
			if (!research_nodes[req])
				log_debug("research_tree: node '[node_id]' has unknown prereq '[req]'")
